-- Hand-fixed (per cmd/migrategen's documented caveat): the raw atlas diff
-- also proposed dropping role_user/user_permission's handwritten UNIQUE
-- NULLS NOT DISTINCT constraints (20260718063900_rbac_unique_nulls_not_distinct) —
-- the diff engine doesn't know ent's schema can't express them. Those
-- DROP/re-ADD statements were removed from this file (and its .down.sql
-- counterpart); this migration only adds member_tiers/point_transactions and
-- the new shop_member.level_id FK.
-- create "member_tiers" table
CREATE TABLE "member_tiers" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying(100) NOT NULL, "min_points" integer NOT NULL DEFAULT 0, "discount_percent" smallint NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "member_tiers_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "member_tiers_discount_percent_check" CHECK ((discount_percent IS NULL) OR ((discount_percent >= 0) AND (discount_percent <= 100))), CONSTRAINT "member_tiers_min_points_check" CHECK (min_points >= 0));
-- create index "membertier_shop_id_min_points" to table: "member_tiers"
CREATE INDEX "membertier_shop_id_min_points" ON "member_tiers" ("shop_id", "min_points");
-- modify "shop_member" table
ALTER TABLE "shop_member" ALTER COLUMN "level_id" TYPE bigint, ADD CONSTRAINT "shop_member_member_tiers_member_tier" FOREIGN KEY ("level_id") REFERENCES "member_tiers" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- create "point_transactions" table
CREATE TABLE "point_transactions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "points_delta" integer NOT NULL, "kind" smallint NOT NULL, "reason" character varying(200) NOT NULL, "shop_id" bigint NOT NULL, "shop_member_id" bigint NOT NULL, "order_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "point_transactions_orders_order" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "point_transactions_shop_member_shop_member" FOREIGN KEY ("shop_member_id") REFERENCES "shop_member" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "point_transactions_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "point_transactions_kind_check" CHECK (kind = ANY (ARRAY[0, 1, 2])));
-- create index "pointtransaction_order_id_kind" to table: "point_transactions"
CREATE UNIQUE INDEX "pointtransaction_order_id_kind" ON "point_transactions" ("order_id", "kind");
-- create index "pointtransaction_shop_id_shop_member_id" to table: "point_transactions"
CREATE INDEX "pointtransaction_shop_id_shop_member_id" ON "point_transactions" ("shop_id", "shop_member_id");
