-- create "categories" table
CREATE TABLE "categories" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying(100) NOT NULL, "slug" character varying(150) NOT NULL, "position" integer NOT NULL DEFAULT 0, "shop_id" bigint NOT NULL, "parent_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "categories_categories_children" FOREIGN KEY ("parent_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "categories_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "category_parent_id" to table: "categories"
CREATE INDEX "category_parent_id" ON "categories" ("parent_id");
-- create index "category_shop_id_name" to table: "categories"
CREATE UNIQUE INDEX "category_shop_id_name" ON "categories" ("shop_id", "name");
-- create index "category_shop_id_slug" to table: "categories"
CREATE UNIQUE INDEX "category_shop_id_slug" ON "categories" ("shop_id", "slug");
-- create "products" table
CREATE TABLE "products" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "title" character varying(200) NOT NULL, "slug" character varying(200) NOT NULL, "description" text NOT NULL DEFAULT '', "status" smallint NOT NULL DEFAULT 0, "meta" jsonb NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "products_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "products_status_check" CHECK (status = ANY (ARRAY[0, 1])));
-- create index "product_shop_id_slug" to table: "products"
CREATE UNIQUE INDEX "product_shop_id_slug" ON "products" ("shop_id", "slug");
-- create index "product_shop_id_status" to table: "products"
CREATE INDEX "product_shop_id_status" ON "products" ("shop_id", "status");
-- create "product_category" table
CREATE TABLE "product_category" ("shop_id" bigint NOT NULL, "product_id" bigint NOT NULL, "category_id" bigint NOT NULL, PRIMARY KEY ("product_id", "category_id"), CONSTRAINT "product_category_categories_category" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "product_category_products_product" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "product_category_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- create index "productcategory_category_id" to table: "product_category"
CREATE INDEX "productcategory_category_id" ON "product_category" ("category_id");
-- create "product_skus" table
CREATE TABLE "product_skus" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "sku_code" character varying(64) NOT NULL, "options" jsonb NOT NULL, "price_amount" bigint NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'TWD', "stock_qty" integer NOT NULL DEFAULT 0, "is_active" boolean NOT NULL DEFAULT true, "product_id" bigint NOT NULL, "shop_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "product_skus_products_skus" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "product_skus_shops_shop" FOREIGN KEY ("shop_id") REFERENCES "shops" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "product_skus_price_amount_check" CHECK (price_amount >= 0), CONSTRAINT "product_skus_stock_qty_check" CHECK (stock_qty >= 0));
-- create index "productsku_product_id" to table: "product_skus"
CREATE INDEX "productsku_product_id" ON "product_skus" ("product_id");
-- create index "productsku_shop_id_sku_code" to table: "product_skus"
CREATE UNIQUE INDEX "productsku_shop_id_sku_code" ON "product_skus" ("shop_id", "sku_code");
