// Code generated by ent, DO NOT EDIT.

package theme

import (
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldUpdatedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldName, v))
}

// LayoutKey applies equality check predicate on the "layout_key" field. It's identical to LayoutKeyEQ.
func LayoutKey(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldLayoutKey, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldUpdatedAt, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldName, v))
}

// LayoutKeyEQ applies the EQ predicate on the "layout_key" field.
func LayoutKeyEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldLayoutKey, v))
}

// LayoutKeyNEQ applies the NEQ predicate on the "layout_key" field.
func LayoutKeyNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldLayoutKey, v))
}

// LayoutKeyIn applies the In predicate on the "layout_key" field.
func LayoutKeyIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldLayoutKey, vs...))
}

// LayoutKeyNotIn applies the NotIn predicate on the "layout_key" field.
func LayoutKeyNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldLayoutKey, vs...))
}

// LayoutKeyGT applies the GT predicate on the "layout_key" field.
func LayoutKeyGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldLayoutKey, v))
}

// LayoutKeyGTE applies the GTE predicate on the "layout_key" field.
func LayoutKeyGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldLayoutKey, v))
}

// LayoutKeyLT applies the LT predicate on the "layout_key" field.
func LayoutKeyLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldLayoutKey, v))
}

// LayoutKeyLTE applies the LTE predicate on the "layout_key" field.
func LayoutKeyLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldLayoutKey, v))
}

// LayoutKeyContains applies the Contains predicate on the "layout_key" field.
func LayoutKeyContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldLayoutKey, v))
}

// LayoutKeyHasPrefix applies the HasPrefix predicate on the "layout_key" field.
func LayoutKeyHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldLayoutKey, v))
}

// LayoutKeyHasSuffix applies the HasSuffix predicate on the "layout_key" field.
func LayoutKeyHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldLayoutKey, v))
}

// LayoutKeyEqualFold applies the EqualFold predicate on the "layout_key" field.
func LayoutKeyEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldLayoutKey, v))
}

// LayoutKeyContainsFold applies the ContainsFold predicate on the "layout_key" field.
func LayoutKeyContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldLayoutKey, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldIsActive, v))
}

// HasPages applies the HasEdge predicate on the "pages" edge.
func HasPages() predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PagesTable, PagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPagesWith applies the HasEdge predicate on the "pages" edge with a given conditions (other predicates).
func HasPagesWith(preds ...predicate.ThemePage) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := newPagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShops applies the HasEdge predicate on the "shops" edge.
func HasShops() predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ShopsTable, ShopsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopsWith applies the HasEdge predicate on the "shops" edge with a given conditions (other predicates).
func HasShopsWith(preds ...predicate.Shop) predicate.Theme {
	return predicate.Theme(func(s *sql.Selector) {
		step := newShopsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.NotPredicates(p))
}
