// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/cart"
	"ksdevworks/ecommerce/api/internal/ent/cartitem"
	"ksdevworks/ecommerce/api/internal/ent/productsku"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CartItemCreate is the builder for creating a CartItem entity.
type CartItemCreate struct {
	config
	mutation *CartItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CartItemCreate) SetCreatedAt(v time.Time) *CartItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CartItemCreate) SetNillableCreatedAt(v *time.Time) *CartItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CartItemCreate) SetUpdatedAt(v time.Time) *CartItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CartItemCreate) SetNillableUpdatedAt(v *time.Time) *CartItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetShopID sets the "shop_id" field.
func (_c *CartItemCreate) SetShopID(v int) *CartItemCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetCartID sets the "cart_id" field.
func (_c *CartItemCreate) SetCartID(v int) *CartItemCreate {
	_c.mutation.SetCartID(v)
	return _c
}

// SetSkuID sets the "sku_id" field.
func (_c *CartItemCreate) SetSkuID(v int) *CartItemCreate {
	_c.mutation.SetSkuID(v)
	return _c
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (_c *CartItemCreate) SetNillableSkuID(v *int) *CartItemCreate {
	if v != nil {
		_c.SetSkuID(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *CartItemCreate) SetQuantity(v int32) *CartItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetPriceAmount sets the "price_amount" field.
func (_c *CartItemCreate) SetPriceAmount(v int64) *CartItemCreate {
	_c.mutation.SetPriceAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *CartItemCreate) SetCurrency(v string) *CartItemCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *CartItemCreate) SetShop(v *Shop) *CartItemCreate {
	return _c.SetShopID(v.ID)
}

// SetCart sets the "cart" edge to the Cart entity.
func (_c *CartItemCreate) SetCart(v *Cart) *CartItemCreate {
	return _c.SetCartID(v.ID)
}

// SetSku sets the "sku" edge to the ProductSKU entity.
func (_c *CartItemCreate) SetSku(v *ProductSKU) *CartItemCreate {
	return _c.SetSkuID(v.ID)
}

// Mutation returns the CartItemMutation object of the builder.
func (_c *CartItemCreate) Mutation() *CartItemMutation {
	return _c.mutation
}

// Save creates the CartItem in the database.
func (_c *CartItemCreate) Save(ctx context.Context) (*CartItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CartItemCreate) SaveX(ctx context.Context) *CartItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CartItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cartitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cartitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CartItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CartItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CartItem.updated_at"`)}
	}
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "CartItem.shop_id"`)}
	}
	if _, ok := _c.mutation.CartID(); !ok {
		return &ValidationError{Name: "cart_id", err: errors.New(`ent: missing required field "CartItem.cart_id"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "CartItem.quantity"`)}
	}
	if _, ok := _c.mutation.PriceAmount(); !ok {
		return &ValidationError{Name: "price_amount", err: errors.New(`ent: missing required field "CartItem.price_amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "CartItem.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := cartitem.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "CartItem.currency": %w`, err)}
		}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "CartItem.shop"`)}
	}
	if len(_c.mutation.CartIDs()) == 0 {
		return &ValidationError{Name: "cart", err: errors.New(`ent: missing required edge "CartItem.cart"`)}
	}
	return nil
}

func (_c *CartItemCreate) sqlSave(ctx context.Context) (*CartItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CartItemCreate) createSpec() (*CartItem, *sqlgraph.CreateSpec) {
	var (
		_node = &CartItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cartitem.Table, sqlgraph.NewFieldSpec(cartitem.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cartitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cartitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(cartitem.FieldQuantity, field.TypeInt32, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.PriceAmount(); ok {
		_spec.SetField(cartitem.FieldPriceAmount, field.TypeInt64, value)
		_node.PriceAmount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(cartitem.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cartitem.ShopTable,
			Columns: []string{cartitem.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CartIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cartitem.CartTable,
			Columns: []string{cartitem.CartColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(cart.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CartID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SkuIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cartitem.SkuTable,
			Columns: []string{cartitem.SkuColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(productsku.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SkuID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CartItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CartItemCreate) OnConflict(opts ...sql.ConflictOption) *CartItemUpsertOne {
	_c.conflict = opts
	return &CartItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CartItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartItemCreate) OnConflictColumns(columns ...string) *CartItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartItemUpsertOne{
		create: _c,
	}
}

type (
	// CartItemUpsertOne is the builder for "upsert"-ing
	//  one CartItem node.
	CartItemUpsertOne struct {
		create *CartItemCreate
	}

	// CartItemUpsert is the "OnConflict" setter.
	CartItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CartItemUpsert) SetUpdatedAt(v time.Time) *CartItemUpsert {
	u.Set(cartitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateUpdatedAt() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldUpdatedAt)
	return u
}

// SetShopID sets the "shop_id" field.
func (u *CartItemUpsert) SetShopID(v int) *CartItemUpsert {
	u.Set(cartitem.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateShopID() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldShopID)
	return u
}

// SetCartID sets the "cart_id" field.
func (u *CartItemUpsert) SetCartID(v int) *CartItemUpsert {
	u.Set(cartitem.FieldCartID, v)
	return u
}

// UpdateCartID sets the "cart_id" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateCartID() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldCartID)
	return u
}

// SetSkuID sets the "sku_id" field.
func (u *CartItemUpsert) SetSkuID(v int) *CartItemUpsert {
	u.Set(cartitem.FieldSkuID, v)
	return u
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateSkuID() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldSkuID)
	return u
}

// ClearSkuID clears the value of the "sku_id" field.
func (u *CartItemUpsert) ClearSkuID() *CartItemUpsert {
	u.SetNull(cartitem.FieldSkuID)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *CartItemUpsert) SetQuantity(v int32) *CartItemUpsert {
	u.Set(cartitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateQuantity() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *CartItemUpsert) AddQuantity(v int32) *CartItemUpsert {
	u.Add(cartitem.FieldQuantity, v)
	return u
}

// SetPriceAmount sets the "price_amount" field.
func (u *CartItemUpsert) SetPriceAmount(v int64) *CartItemUpsert {
	u.Set(cartitem.FieldPriceAmount, v)
	return u
}

// UpdatePriceAmount sets the "price_amount" field to the value that was provided on create.
func (u *CartItemUpsert) UpdatePriceAmount() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldPriceAmount)
	return u
}

// AddPriceAmount adds v to the "price_amount" field.
func (u *CartItemUpsert) AddPriceAmount(v int64) *CartItemUpsert {
	u.Add(cartitem.FieldPriceAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *CartItemUpsert) SetCurrency(v string) *CartItemUpsert {
	u.Set(cartitem.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CartItemUpsert) UpdateCurrency() *CartItemUpsert {
	u.SetExcluded(cartitem.FieldCurrency)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CartItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CartItemUpsertOne) UpdateNewValues() *CartItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cartitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CartItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CartItemUpsertOne) Ignore() *CartItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartItemUpsertOne) DoNothing() *CartItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartItemCreate.OnConflict
// documentation for more info.
func (u *CartItemUpsertOne) Update(set func(*CartItemUpsert)) *CartItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartItemUpsertOne) SetUpdatedAt(v time.Time) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateUpdatedAt() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *CartItemUpsertOne) SetShopID(v int) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateShopID() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateShopID()
	})
}

// SetCartID sets the "cart_id" field.
func (u *CartItemUpsertOne) SetCartID(v int) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetCartID(v)
	})
}

// UpdateCartID sets the "cart_id" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateCartID() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateCartID()
	})
}

// SetSkuID sets the "sku_id" field.
func (u *CartItemUpsertOne) SetSkuID(v int) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetSkuID(v)
	})
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateSkuID() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateSkuID()
	})
}

// ClearSkuID clears the value of the "sku_id" field.
func (u *CartItemUpsertOne) ClearSkuID() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.ClearSkuID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *CartItemUpsertOne) SetQuantity(v int32) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *CartItemUpsertOne) AddQuantity(v int32) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateQuantity() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetPriceAmount sets the "price_amount" field.
func (u *CartItemUpsertOne) SetPriceAmount(v int64) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetPriceAmount(v)
	})
}

// AddPriceAmount adds v to the "price_amount" field.
func (u *CartItemUpsertOne) AddPriceAmount(v int64) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.AddPriceAmount(v)
	})
}

// UpdatePriceAmount sets the "price_amount" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdatePriceAmount() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdatePriceAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CartItemUpsertOne) SetCurrency(v string) *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CartItemUpsertOne) UpdateCurrency() *CartItemUpsertOne {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateCurrency()
	})
}

// Exec executes the query.
func (u *CartItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CartItemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CartItemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CartItemCreateBulk is the builder for creating many CartItem entities in bulk.
type CartItemCreateBulk struct {
	config
	err      error
	builders []*CartItemCreate
	conflict []sql.ConflictOption
}

// Save creates the CartItem entities in the database.
func (_c *CartItemCreateBulk) Save(ctx context.Context) ([]*CartItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CartItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CartItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CartItemCreateBulk) SaveX(ctx context.Context) []*CartItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CartItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CartItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CartItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CartItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CartItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *CartItemUpsertBulk {
	_c.conflict = opts
	return &CartItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CartItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CartItemCreateBulk) OnConflictColumns(columns ...string) *CartItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CartItemUpsertBulk{
		create: _c,
	}
}

// CartItemUpsertBulk is the builder for "upsert"-ing
// a bulk of CartItem nodes.
type CartItemUpsertBulk struct {
	create *CartItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CartItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CartItemUpsertBulk) UpdateNewValues() *CartItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cartitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CartItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CartItemUpsertBulk) Ignore() *CartItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CartItemUpsertBulk) DoNothing() *CartItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CartItemCreateBulk.OnConflict
// documentation for more info.
func (u *CartItemUpsertBulk) Update(set func(*CartItemUpsert)) *CartItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CartItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CartItemUpsertBulk) SetUpdatedAt(v time.Time) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateUpdatedAt() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *CartItemUpsertBulk) SetShopID(v int) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateShopID() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateShopID()
	})
}

// SetCartID sets the "cart_id" field.
func (u *CartItemUpsertBulk) SetCartID(v int) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetCartID(v)
	})
}

// UpdateCartID sets the "cart_id" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateCartID() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateCartID()
	})
}

// SetSkuID sets the "sku_id" field.
func (u *CartItemUpsertBulk) SetSkuID(v int) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetSkuID(v)
	})
}

// UpdateSkuID sets the "sku_id" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateSkuID() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateSkuID()
	})
}

// ClearSkuID clears the value of the "sku_id" field.
func (u *CartItemUpsertBulk) ClearSkuID() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.ClearSkuID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *CartItemUpsertBulk) SetQuantity(v int32) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *CartItemUpsertBulk) AddQuantity(v int32) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateQuantity() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetPriceAmount sets the "price_amount" field.
func (u *CartItemUpsertBulk) SetPriceAmount(v int64) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetPriceAmount(v)
	})
}

// AddPriceAmount adds v to the "price_amount" field.
func (u *CartItemUpsertBulk) AddPriceAmount(v int64) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.AddPriceAmount(v)
	})
}

// UpdatePriceAmount sets the "price_amount" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdatePriceAmount() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdatePriceAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *CartItemUpsertBulk) SetCurrency(v string) *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *CartItemUpsertBulk) UpdateCurrency() *CartItemUpsertBulk {
	return u.Update(func(s *CartItemUpsert) {
		s.UpdateCurrency()
	})
}

// Exec executes the query.
func (u *CartItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CartItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CartItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CartItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
