// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/member"
	"ksdevworks/ecommerce/api/internal/ent/order"
	"ksdevworks/ecommerce/api/internal/ent/orderitem"
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdate) SetUpdatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *OrderUpdate) SetShopID(v int) *OrderUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableShopID(v *int) *OrderUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *OrderUpdate) SetMemberID(v int) *OrderUpdate {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableMemberID(v *int) *OrderUpdate {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v int16) *OrderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *int16) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderUpdate) AddStatus(v int16) *OrderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *OrderUpdate) SetPaymentStatus(v int16) *OrderUpdate {
	_u.mutation.ResetPaymentStatus()
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePaymentStatus(v *int16) *OrderUpdate {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// AddPaymentStatus adds value to the "payment_status" field.
func (_u *OrderUpdate) AddPaymentStatus(v int16) *OrderUpdate {
	_u.mutation.AddPaymentStatus(v)
	return _u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_u *OrderUpdate) SetFulfillmentStatus(v int16) *OrderUpdate {
	_u.mutation.ResetFulfillmentStatus()
	_u.mutation.SetFulfillmentStatus(v)
	return _u
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableFulfillmentStatus(v *int16) *OrderUpdate {
	if v != nil {
		_u.SetFulfillmentStatus(*v)
	}
	return _u
}

// AddFulfillmentStatus adds value to the "fulfillment_status" field.
func (_u *OrderUpdate) AddFulfillmentStatus(v int16) *OrderUpdate {
	_u.mutation.AddFulfillmentStatus(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *OrderUpdate) SetCurrency(v string) *OrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCurrency(v *string) *OrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdate) SetTotalAmount(v int64) *OrderUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTotalAmount(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdate) AddTotalAmount(v int64) *OrderUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetShippingAddress sets the "shipping_address" field.
func (_u *OrderUpdate) SetShippingAddress(v json.RawMessage) *OrderUpdate {
	_u.mutation.SetShippingAddress(v)
	return _u
}

// AppendShippingAddress appends value to the "shipping_address" field.
func (_u *OrderUpdate) AppendShippingAddress(v json.RawMessage) *OrderUpdate {
	_u.mutation.AppendShippingAddress(v)
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *OrderUpdate) SetCancelledAt(v time.Time) *OrderUpdate {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCancelledAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *OrderUpdate) ClearCancelledAt() *OrderUpdate {
	_u.mutation.ClearCancelledAt()
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *OrderUpdate) SetShop(v *Shop) *OrderUpdate {
	return _u.SetShopID(v.ID)
}

// SetMember sets the "member" edge to the Member entity.
func (_u *OrderUpdate) SetMember(v *Member) *OrderUpdate {
	return _u.SetMemberID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdate) AddItemIDs(ids ...int) *OrderUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdate) AddItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *OrderUpdate) ClearShop() *OrderUpdate {
	_u.mutation.ClearShop()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *OrderUpdate) ClearMember() *OrderUpdate {
	_u.mutation.ClearMember()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdate) ClearItems() *OrderUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdate) RemoveItemIDs(ids ...int) *OrderUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdate) RemoveItems(v ...*OrderItem) *OrderUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := order.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Order.currency": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.shop"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.member"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(order.FieldPaymentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedPaymentStatus(); ok {
		_spec.AddField(order.FieldPaymentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.FulfillmentStatus(); ok {
		_spec.SetField(order.FieldFulfillmentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedFulfillmentStatus(); ok {
		_spec.AddField(order.FieldFulfillmentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(order.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ShippingAddress(); ok {
		_spec.SetField(order.FieldShippingAddress, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedShippingAddress(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldShippingAddress, value)
		})
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(order.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(order.FieldCancelledAt, field.TypeTime)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ShopTable,
			Columns: []string{order.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ShopTable,
			Columns: []string{order.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.MemberTable,
			Columns: []string{order.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.MemberTable,
			Columns: []string{order.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *OrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderUpdateOne) SetUpdatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *OrderUpdateOne) SetShopID(v int) *OrderUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableShopID(v *int) *OrderUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetMemberID sets the "member_id" field.
func (_u *OrderUpdateOne) SetMemberID(v int) *OrderUpdateOne {
	_u.mutation.SetMemberID(v)
	return _u
}

// SetNillableMemberID sets the "member_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableMemberID(v *int) *OrderUpdateOne {
	if v != nil {
		_u.SetMemberID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v int16) *OrderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *int16) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *OrderUpdateOne) AddStatus(v int16) *OrderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPaymentStatus sets the "payment_status" field.
func (_u *OrderUpdateOne) SetPaymentStatus(v int16) *OrderUpdateOne {
	_u.mutation.ResetPaymentStatus()
	_u.mutation.SetPaymentStatus(v)
	return _u
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePaymentStatus(v *int16) *OrderUpdateOne {
	if v != nil {
		_u.SetPaymentStatus(*v)
	}
	return _u
}

// AddPaymentStatus adds value to the "payment_status" field.
func (_u *OrderUpdateOne) AddPaymentStatus(v int16) *OrderUpdateOne {
	_u.mutation.AddPaymentStatus(v)
	return _u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_u *OrderUpdateOne) SetFulfillmentStatus(v int16) *OrderUpdateOne {
	_u.mutation.ResetFulfillmentStatus()
	_u.mutation.SetFulfillmentStatus(v)
	return _u
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableFulfillmentStatus(v *int16) *OrderUpdateOne {
	if v != nil {
		_u.SetFulfillmentStatus(*v)
	}
	return _u
}

// AddFulfillmentStatus adds value to the "fulfillment_status" field.
func (_u *OrderUpdateOne) AddFulfillmentStatus(v int16) *OrderUpdateOne {
	_u.mutation.AddFulfillmentStatus(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *OrderUpdateOne) SetCurrency(v string) *OrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCurrency(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetTotalAmount sets the "total_amount" field.
func (_u *OrderUpdateOne) SetTotalAmount(v int64) *OrderUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "total_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTotalAmount(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "total_amount" field.
func (_u *OrderUpdateOne) AddTotalAmount(v int64) *OrderUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetShippingAddress sets the "shipping_address" field.
func (_u *OrderUpdateOne) SetShippingAddress(v json.RawMessage) *OrderUpdateOne {
	_u.mutation.SetShippingAddress(v)
	return _u
}

// AppendShippingAddress appends value to the "shipping_address" field.
func (_u *OrderUpdateOne) AppendShippingAddress(v json.RawMessage) *OrderUpdateOne {
	_u.mutation.AppendShippingAddress(v)
	return _u
}

// SetCancelledAt sets the "cancelled_at" field.
func (_u *OrderUpdateOne) SetCancelledAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetCancelledAt(v)
	return _u
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCancelledAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetCancelledAt(*v)
	}
	return _u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (_u *OrderUpdateOne) ClearCancelledAt() *OrderUpdateOne {
	_u.mutation.ClearCancelledAt()
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *OrderUpdateOne) SetShop(v *Shop) *OrderUpdateOne {
	return _u.SetShopID(v.ID)
}

// SetMember sets the "member" edge to the Member entity.
func (_u *OrderUpdateOne) SetMember(v *Member) *OrderUpdateOne {
	return _u.SetMemberID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_u *OrderUpdateOne) AddItemIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) AddItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *OrderUpdateOne) ClearShop() *OrderUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *OrderUpdateOne) ClearMember() *OrderUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// ClearItems clears all "items" edges to the OrderItem entity.
func (_u *OrderUpdateOne) ClearItems() *OrderUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OrderItem entities by IDs.
func (_u *OrderUpdateOne) RemoveItemIDs(ids ...int) *OrderUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OrderItem entities.
func (_u *OrderUpdateOne) RemoveItems(v ...*OrderItem) *OrderUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := order.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.Currency(); ok {
		if err := order.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Order.currency": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.shop"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.member"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *OrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *OrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(order.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.PaymentStatus(); ok {
		_spec.SetField(order.FieldPaymentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedPaymentStatus(); ok {
		_spec.AddField(order.FieldPaymentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.FulfillmentStatus(); ok {
		_spec.SetField(order.FieldFulfillmentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedFulfillmentStatus(); ok {
		_spec.AddField(order.FieldFulfillmentStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(order.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(order.FieldTotalAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ShippingAddress(); ok {
		_spec.SetField(order.FieldShippingAddress, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedShippingAddress(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, order.FieldShippingAddress, value)
		})
	}
	if value, ok := _u.mutation.CancelledAt(); ok {
		_spec.SetField(order.FieldCancelledAt, field.TypeTime, value)
	}
	if _u.mutation.CancelledAtCleared() {
		_spec.ClearField(order.FieldCancelledAt, field.TypeTime)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ShopTable,
			Columns: []string{order.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ShopTable,
			Columns: []string{order.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.MemberTable,
			Columns: []string{order.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.MemberTable,
			Columns: []string{order.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
