// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/member"
	"ksdevworks/ecommerce/api/internal/ent/order"
	"ksdevworks/ecommerce/api/internal/ent/orderitem"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCreatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCreate) SetUpdatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableUpdatedAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetShopID sets the "shop_id" field.
func (_c *OrderCreate) SetShopID(v int) *OrderCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetMemberID sets the "member_id" field.
func (_c *OrderCreate) SetMemberID(v int) *OrderCreate {
	_c.mutation.SetMemberID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v int16) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *int16) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentStatus sets the "payment_status" field.
func (_c *OrderCreate) SetPaymentStatus(v int16) *OrderCreate {
	_c.mutation.SetPaymentStatus(v)
	return _c
}

// SetNillablePaymentStatus sets the "payment_status" field if the given value is not nil.
func (_c *OrderCreate) SetNillablePaymentStatus(v *int16) *OrderCreate {
	if v != nil {
		_c.SetPaymentStatus(*v)
	}
	return _c
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (_c *OrderCreate) SetFulfillmentStatus(v int16) *OrderCreate {
	_c.mutation.SetFulfillmentStatus(v)
	return _c
}

// SetNillableFulfillmentStatus sets the "fulfillment_status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableFulfillmentStatus(v *int16) *OrderCreate {
	if v != nil {
		_c.SetFulfillmentStatus(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *OrderCreate) SetCurrency(v string) *OrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *OrderCreate) SetTotalAmount(v int64) *OrderCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetShippingAddress sets the "shipping_address" field.
func (_c *OrderCreate) SetShippingAddress(v json.RawMessage) *OrderCreate {
	_c.mutation.SetShippingAddress(v)
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *OrderCreate) SetCancelledAt(v time.Time) *OrderCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCancelledAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *OrderCreate) SetShop(v *Shop) *OrderCreate {
	return _c.SetShopID(v.ID)
}

// SetMember sets the "member" edge to the Member entity.
func (_c *OrderCreate) SetMember(v *Member) *OrderCreate {
	return _c.SetMemberID(v.ID)
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_c *OrderCreate) AddItemIDs(ids ...int) *OrderCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_c *OrderCreate) AddItems(v ...*OrderItem) *OrderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := order.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := order.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		v := order.DefaultPaymentStatus
		_c.mutation.SetPaymentStatus(v)
	}
	if _, ok := _c.mutation.FulfillmentStatus(); !ok {
		v := order.DefaultFulfillmentStatus
		_c.mutation.SetFulfillmentStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Order.updated_at"`)}
	}
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "Order.shop_id"`)}
	}
	if _, ok := _c.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "Order.member_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if _, ok := _c.mutation.PaymentStatus(); !ok {
		return &ValidationError{Name: "payment_status", err: errors.New(`ent: missing required field "Order.payment_status"`)}
	}
	if _, ok := _c.mutation.FulfillmentStatus(); !ok {
		return &ValidationError{Name: "fulfillment_status", err: errors.New(`ent: missing required field "Order.fulfillment_status"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Order.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := order.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Order.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "Order.total_amount"`)}
	}
	if _, ok := _c.mutation.ShippingAddress(); !ok {
		return &ValidationError{Name: "shipping_address", err: errors.New(`ent: missing required field "Order.shipping_address"`)}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "Order.shop"`)}
	}
	if len(_c.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "Order.member"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeInt16, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentStatus(); ok {
		_spec.SetField(order.FieldPaymentStatus, field.TypeInt16, value)
		_node.PaymentStatus = value
	}
	if value, ok := _c.mutation.FulfillmentStatus(); ok {
		_spec.SetField(order.FieldFulfillmentStatus, field.TypeInt16, value)
		_node.FulfillmentStatus = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(order.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(order.FieldTotalAmount, field.TypeInt64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.ShippingAddress(); ok {
		_spec.SetField(order.FieldShippingAddress, field.TypeJSON, value)
		_node.ShippingAddress = value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(order.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.ShopTable,
			Columns: []string{order.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   order.MemberTable,
			Columns: []string{order.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreate) OnConflict(opts ...sql.ConflictOption) *OrderUpsertOne {
	_c.conflict = opts
	return &OrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreate) OnConflictColumns(columns ...string) *OrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertOne{
		create: _c,
	}
}

type (
	// OrderUpsertOne is the builder for "upsert"-ing
	//  one Order node.
	OrderUpsertOne struct {
		create *OrderCreate
	}

	// OrderUpsert is the "OnConflict" setter.
	OrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsert) SetUpdatedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUpdatedAt() *OrderUpsert {
	u.SetExcluded(order.FieldUpdatedAt)
	return u
}

// SetShopID sets the "shop_id" field.
func (u *OrderUpsert) SetShopID(v int) *OrderUpsert {
	u.Set(order.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateShopID() *OrderUpsert {
	u.SetExcluded(order.FieldShopID)
	return u
}

// SetMemberID sets the "member_id" field.
func (u *OrderUpsert) SetMemberID(v int) *OrderUpsert {
	u.Set(order.FieldMemberID, v)
	return u
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateMemberID() *OrderUpsert {
	u.SetExcluded(order.FieldMemberID)
	return u
}

// SetStatus sets the "status" field.
func (u *OrderUpsert) SetStatus(v int16) *OrderUpsert {
	u.Set(order.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateStatus() *OrderUpsert {
	u.SetExcluded(order.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsert) AddStatus(v int16) *OrderUpsert {
	u.Add(order.FieldStatus, v)
	return u
}

// SetPaymentStatus sets the "payment_status" field.
func (u *OrderUpsert) SetPaymentStatus(v int16) *OrderUpsert {
	u.Set(order.FieldPaymentStatus, v)
	return u
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *OrderUpsert) UpdatePaymentStatus() *OrderUpsert {
	u.SetExcluded(order.FieldPaymentStatus)
	return u
}

// AddPaymentStatus adds v to the "payment_status" field.
func (u *OrderUpsert) AddPaymentStatus(v int16) *OrderUpsert {
	u.Add(order.FieldPaymentStatus, v)
	return u
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *OrderUpsert) SetFulfillmentStatus(v int16) *OrderUpsert {
	u.Set(order.FieldFulfillmentStatus, v)
	return u
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateFulfillmentStatus() *OrderUpsert {
	u.SetExcluded(order.FieldFulfillmentStatus)
	return u
}

// AddFulfillmentStatus adds v to the "fulfillment_status" field.
func (u *OrderUpsert) AddFulfillmentStatus(v int16) *OrderUpsert {
	u.Add(order.FieldFulfillmentStatus, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *OrderUpsert) SetCurrency(v string) *OrderUpsert {
	u.Set(order.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *OrderUpsert) UpdateCurrency() *OrderUpsert {
	u.SetExcluded(order.FieldCurrency)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *OrderUpsert) SetTotalAmount(v int64) *OrderUpsert {
	u.Set(order.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateTotalAmount() *OrderUpsert {
	u.SetExcluded(order.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *OrderUpsert) AddTotalAmount(v int64) *OrderUpsert {
	u.Add(order.FieldTotalAmount, v)
	return u
}

// SetShippingAddress sets the "shipping_address" field.
func (u *OrderUpsert) SetShippingAddress(v json.RawMessage) *OrderUpsert {
	u.Set(order.FieldShippingAddress, v)
	return u
}

// UpdateShippingAddress sets the "shipping_address" field to the value that was provided on create.
func (u *OrderUpsert) UpdateShippingAddress() *OrderUpsert {
	u.SetExcluded(order.FieldShippingAddress)
	return u
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *OrderUpsert) SetCancelledAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldCancelledAt, v)
	return u
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateCancelledAt() *OrderUpsert {
	u.SetExcluded(order.FieldCancelledAt)
	return u
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *OrderUpsert) ClearCancelledAt() *OrderUpsert {
	u.SetNull(order.FieldCancelledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertOne) UpdateNewValues() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(order.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderUpsertOne) Ignore() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertOne) DoNothing() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreate.OnConflict
// documentation for more info.
func (u *OrderUpsertOne) Update(set func(*OrderUpsert)) *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertOne) SetUpdatedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUpdatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *OrderUpsertOne) SetShopID(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateShopID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateShopID()
	})
}

// SetMemberID sets the "member_id" field.
func (u *OrderUpsertOne) SetMemberID(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateMemberID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateMemberID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertOne) SetStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsertOne) AddStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentStatus sets the "payment_status" field.
func (u *OrderUpsertOne) SetPaymentStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentStatus(v)
	})
}

// AddPaymentStatus adds v to the "payment_status" field.
func (u *OrderUpsertOne) AddPaymentStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddPaymentStatus(v)
	})
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdatePaymentStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentStatus()
	})
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *OrderUpsertOne) SetFulfillmentStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetFulfillmentStatus(v)
	})
}

// AddFulfillmentStatus adds v to the "fulfillment_status" field.
func (u *OrderUpsertOne) AddFulfillmentStatus(v int16) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddFulfillmentStatus(v)
	})
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateFulfillmentStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateFulfillmentStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *OrderUpsertOne) SetCurrency(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateCurrency() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *OrderUpsertOne) SetTotalAmount(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *OrderUpsertOne) AddTotalAmount(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateTotalAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetShippingAddress sets the "shipping_address" field.
func (u *OrderUpsertOne) SetShippingAddress(v json.RawMessage) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetShippingAddress(v)
	})
}

// UpdateShippingAddress sets the "shipping_address" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateShippingAddress() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateShippingAddress()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *OrderUpsertOne) SetCancelledAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateCancelledAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *OrderUpsertOne) ClearCancelledAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearCancelledAt()
	})
}

// Exec executes the query.
func (u *OrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
	conflict []sql.ConflictOption
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderUpsertBulk {
	_c.conflict = opts
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflictColumns(columns ...string) *OrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OrderUpsertBulk is the builder for "upsert"-ing
// a bulk of Order nodes.
type OrderUpsertBulk struct {
	create *OrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertBulk) UpdateNewValues() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(order.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderUpsertBulk) Ignore() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertBulk) DoNothing() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreateBulk.OnConflict
// documentation for more info.
func (u *OrderUpsertBulk) Update(set func(*OrderUpsert)) *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertBulk) SetUpdatedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUpdatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *OrderUpsertBulk) SetShopID(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateShopID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateShopID()
	})
}

// SetMemberID sets the "member_id" field.
func (u *OrderUpsertBulk) SetMemberID(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetMemberID(v)
	})
}

// UpdateMemberID sets the "member_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateMemberID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateMemberID()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertBulk) SetStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *OrderUpsertBulk) AddStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentStatus sets the "payment_status" field.
func (u *OrderUpsertBulk) SetPaymentStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentStatus(v)
	})
}

// AddPaymentStatus adds v to the "payment_status" field.
func (u *OrderUpsertBulk) AddPaymentStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddPaymentStatus(v)
	})
}

// UpdatePaymentStatus sets the "payment_status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdatePaymentStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentStatus()
	})
}

// SetFulfillmentStatus sets the "fulfillment_status" field.
func (u *OrderUpsertBulk) SetFulfillmentStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetFulfillmentStatus(v)
	})
}

// AddFulfillmentStatus adds v to the "fulfillment_status" field.
func (u *OrderUpsertBulk) AddFulfillmentStatus(v int16) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddFulfillmentStatus(v)
	})
}

// UpdateFulfillmentStatus sets the "fulfillment_status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateFulfillmentStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateFulfillmentStatus()
	})
}

// SetCurrency sets the "currency" field.
func (u *OrderUpsertBulk) SetCurrency(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateCurrency() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *OrderUpsertBulk) SetTotalAmount(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *OrderUpsertBulk) AddTotalAmount(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateTotalAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetShippingAddress sets the "shipping_address" field.
func (u *OrderUpsertBulk) SetShippingAddress(v json.RawMessage) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetShippingAddress(v)
	})
}

// UpdateShippingAddress sets the "shipping_address" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateShippingAddress() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateShippingAddress()
	})
}

// SetCancelledAt sets the "cancelled_at" field.
func (u *OrderUpsertBulk) SetCancelledAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetCancelledAt(v)
	})
}

// UpdateCancelledAt sets the "cancelled_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateCancelledAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCancelledAt()
	})
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (u *OrderUpsertBulk) ClearCancelledAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearCancelledAt()
	})
}

// Exec executes the query.
func (u *OrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
