// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/page"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PageCreate is the builder for creating a Page entity.
type PageCreate struct {
	config
	mutation *PageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PageCreate) SetCreatedAt(v time.Time) *PageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PageCreate) SetNillableCreatedAt(v *time.Time) *PageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PageCreate) SetUpdatedAt(v time.Time) *PageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PageCreate) SetNillableUpdatedAt(v *time.Time) *PageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetShopID sets the "shop_id" field.
func (_c *PageCreate) SetShopID(v int) *PageCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetTypeKey sets the "type_key" field.
func (_c *PageCreate) SetTypeKey(v string) *PageCreate {
	_c.mutation.SetTypeKey(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PageCreate) SetTitle(v string) *PageCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PageCreate) SetNillableTitle(v *string) *PageCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *PageCreate) SetSlug(v string) *PageCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PageCreate) SetStatus(v int16) *PageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PageCreate) SetNillableStatus(v *int16) *PageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetContentJSON sets the "content_json" field.
func (_c *PageCreate) SetContentJSON(v json.RawMessage) *PageCreate {
	_c.mutation.SetContentJSON(v)
	return _c
}

// SetPublishedJSON sets the "published_json" field.
func (_c *PageCreate) SetPublishedJSON(v json.RawMessage) *PageCreate {
	_c.mutation.SetPublishedJSON(v)
	return _c
}

// SetMeta sets the "meta" field.
func (_c *PageCreate) SetMeta(v json.RawMessage) *PageCreate {
	_c.mutation.SetMeta(v)
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *PageCreate) SetShop(v *Shop) *PageCreate {
	return _c.SetShopID(v.ID)
}

// Mutation returns the PageMutation object of the builder.
func (_c *PageCreate) Mutation() *PageMutation {
	return _c.mutation
}

// Save creates the Page in the database.
func (_c *PageCreate) Save(ctx context.Context) (*Page, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PageCreate) SaveX(ctx context.Context) *Page {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := page.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := page.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := page.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := page.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ContentJSON(); !ok {
		v := page.DefaultContentJSON
		_c.mutation.SetContentJSON(v)
	}
	if _, ok := _c.mutation.Meta(); !ok {
		v := page.DefaultMeta
		_c.mutation.SetMeta(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Page.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Page.updated_at"`)}
	}
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "Page.shop_id"`)}
	}
	if _, ok := _c.mutation.TypeKey(); !ok {
		return &ValidationError{Name: "type_key", err: errors.New(`ent: missing required field "Page.type_key"`)}
	}
	if v, ok := _c.mutation.TypeKey(); ok {
		if err := page.TypeKeyValidator(v); err != nil {
			return &ValidationError{Name: "type_key", err: fmt.Errorf(`ent: validator failed for field "Page.type_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Page.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Page.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := page.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Page.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Page.status"`)}
	}
	if _, ok := _c.mutation.ContentJSON(); !ok {
		return &ValidationError{Name: "content_json", err: errors.New(`ent: missing required field "Page.content_json"`)}
	}
	if _, ok := _c.mutation.Meta(); !ok {
		return &ValidationError{Name: "meta", err: errors.New(`ent: missing required field "Page.meta"`)}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "Page.shop"`)}
	}
	return nil
}

func (_c *PageCreate) sqlSave(ctx context.Context) (*Page, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PageCreate) createSpec() (*Page, *sqlgraph.CreateSpec) {
	var (
		_node = &Page{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(page.Table, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(page.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(page.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TypeKey(); ok {
		_spec.SetField(page.FieldTypeKey, field.TypeString, value)
		_node.TypeKey = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(page.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(page.FieldStatus, field.TypeInt16, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ContentJSON(); ok {
		_spec.SetField(page.FieldContentJSON, field.TypeJSON, value)
		_node.ContentJSON = value
	}
	if value, ok := _c.mutation.PublishedJSON(); ok {
		_spec.SetField(page.FieldPublishedJSON, field.TypeJSON, value)
		_node.PublishedJSON = value
	}
	if value, ok := _c.mutation.Meta(); ok {
		_spec.SetField(page.FieldMeta, field.TypeJSON, value)
		_node.Meta = value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ShopTable,
			Columns: []string{page.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Page.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PageCreate) OnConflict(opts ...sql.ConflictOption) *PageUpsertOne {
	_c.conflict = opts
	return &PageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Page.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PageCreate) OnConflictColumns(columns ...string) *PageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PageUpsertOne{
		create: _c,
	}
}

type (
	// PageUpsertOne is the builder for "upsert"-ing
	//  one Page node.
	PageUpsertOne struct {
		create *PageCreate
	}

	// PageUpsert is the "OnConflict" setter.
	PageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PageUpsert) SetUpdatedAt(v time.Time) *PageUpsert {
	u.Set(page.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PageUpsert) UpdateUpdatedAt() *PageUpsert {
	u.SetExcluded(page.FieldUpdatedAt)
	return u
}

// SetShopID sets the "shop_id" field.
func (u *PageUpsert) SetShopID(v int) *PageUpsert {
	u.Set(page.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *PageUpsert) UpdateShopID() *PageUpsert {
	u.SetExcluded(page.FieldShopID)
	return u
}

// SetTypeKey sets the "type_key" field.
func (u *PageUpsert) SetTypeKey(v string) *PageUpsert {
	u.Set(page.FieldTypeKey, v)
	return u
}

// UpdateTypeKey sets the "type_key" field to the value that was provided on create.
func (u *PageUpsert) UpdateTypeKey() *PageUpsert {
	u.SetExcluded(page.FieldTypeKey)
	return u
}

// SetTitle sets the "title" field.
func (u *PageUpsert) SetTitle(v string) *PageUpsert {
	u.Set(page.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PageUpsert) UpdateTitle() *PageUpsert {
	u.SetExcluded(page.FieldTitle)
	return u
}

// SetSlug sets the "slug" field.
func (u *PageUpsert) SetSlug(v string) *PageUpsert {
	u.Set(page.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PageUpsert) UpdateSlug() *PageUpsert {
	u.SetExcluded(page.FieldSlug)
	return u
}

// SetStatus sets the "status" field.
func (u *PageUpsert) SetStatus(v int16) *PageUpsert {
	u.Set(page.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PageUpsert) UpdateStatus() *PageUpsert {
	u.SetExcluded(page.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *PageUpsert) AddStatus(v int16) *PageUpsert {
	u.Add(page.FieldStatus, v)
	return u
}

// SetContentJSON sets the "content_json" field.
func (u *PageUpsert) SetContentJSON(v json.RawMessage) *PageUpsert {
	u.Set(page.FieldContentJSON, v)
	return u
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *PageUpsert) UpdateContentJSON() *PageUpsert {
	u.SetExcluded(page.FieldContentJSON)
	return u
}

// SetPublishedJSON sets the "published_json" field.
func (u *PageUpsert) SetPublishedJSON(v json.RawMessage) *PageUpsert {
	u.Set(page.FieldPublishedJSON, v)
	return u
}

// UpdatePublishedJSON sets the "published_json" field to the value that was provided on create.
func (u *PageUpsert) UpdatePublishedJSON() *PageUpsert {
	u.SetExcluded(page.FieldPublishedJSON)
	return u
}

// ClearPublishedJSON clears the value of the "published_json" field.
func (u *PageUpsert) ClearPublishedJSON() *PageUpsert {
	u.SetNull(page.FieldPublishedJSON)
	return u
}

// SetMeta sets the "meta" field.
func (u *PageUpsert) SetMeta(v json.RawMessage) *PageUpsert {
	u.Set(page.FieldMeta, v)
	return u
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *PageUpsert) UpdateMeta() *PageUpsert {
	u.SetExcluded(page.FieldMeta)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Page.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PageUpsertOne) UpdateNewValues() *PageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(page.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Page.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PageUpsertOne) Ignore() *PageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PageUpsertOne) DoNothing() *PageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PageCreate.OnConflict
// documentation for more info.
func (u *PageUpsertOne) Update(set func(*PageUpsert)) *PageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PageUpsertOne) SetUpdatedAt(v time.Time) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateUpdatedAt() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *PageUpsertOne) SetShopID(v int) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateShopID() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateShopID()
	})
}

// SetTypeKey sets the "type_key" field.
func (u *PageUpsertOne) SetTypeKey(v string) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetTypeKey(v)
	})
}

// UpdateTypeKey sets the "type_key" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateTypeKey() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateTypeKey()
	})
}

// SetTitle sets the "title" field.
func (u *PageUpsertOne) SetTitle(v string) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateTitle() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateTitle()
	})
}

// SetSlug sets the "slug" field.
func (u *PageUpsertOne) SetSlug(v string) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateSlug() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *PageUpsertOne) SetStatus(v int16) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *PageUpsertOne) AddStatus(v int16) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateStatus() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateStatus()
	})
}

// SetContentJSON sets the "content_json" field.
func (u *PageUpsertOne) SetContentJSON(v json.RawMessage) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetContentJSON(v)
	})
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateContentJSON() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateContentJSON()
	})
}

// SetPublishedJSON sets the "published_json" field.
func (u *PageUpsertOne) SetPublishedJSON(v json.RawMessage) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetPublishedJSON(v)
	})
}

// UpdatePublishedJSON sets the "published_json" field to the value that was provided on create.
func (u *PageUpsertOne) UpdatePublishedJSON() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdatePublishedJSON()
	})
}

// ClearPublishedJSON clears the value of the "published_json" field.
func (u *PageUpsertOne) ClearPublishedJSON() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.ClearPublishedJSON()
	})
}

// SetMeta sets the "meta" field.
func (u *PageUpsertOne) SetMeta(v json.RawMessage) *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.SetMeta(v)
	})
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *PageUpsertOne) UpdateMeta() *PageUpsertOne {
	return u.Update(func(s *PageUpsert) {
		s.UpdateMeta()
	})
}

// Exec executes the query.
func (u *PageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PageCreateBulk is the builder for creating many Page entities in bulk.
type PageCreateBulk struct {
	config
	err      error
	builders []*PageCreate
	conflict []sql.ConflictOption
}

// Save creates the Page entities in the database.
func (_c *PageCreateBulk) Save(ctx context.Context) ([]*Page, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Page, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PageCreateBulk) SaveX(ctx context.Context) []*Page {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Page.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PageCreateBulk) OnConflict(opts ...sql.ConflictOption) *PageUpsertBulk {
	_c.conflict = opts
	return &PageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Page.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PageCreateBulk) OnConflictColumns(columns ...string) *PageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PageUpsertBulk{
		create: _c,
	}
}

// PageUpsertBulk is the builder for "upsert"-ing
// a bulk of Page nodes.
type PageUpsertBulk struct {
	create *PageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Page.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PageUpsertBulk) UpdateNewValues() *PageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(page.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Page.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PageUpsertBulk) Ignore() *PageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PageUpsertBulk) DoNothing() *PageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PageCreateBulk.OnConflict
// documentation for more info.
func (u *PageUpsertBulk) Update(set func(*PageUpsert)) *PageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PageUpsertBulk) SetUpdatedAt(v time.Time) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateUpdatedAt() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetShopID sets the "shop_id" field.
func (u *PageUpsertBulk) SetShopID(v int) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateShopID() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateShopID()
	})
}

// SetTypeKey sets the "type_key" field.
func (u *PageUpsertBulk) SetTypeKey(v string) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetTypeKey(v)
	})
}

// UpdateTypeKey sets the "type_key" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateTypeKey() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateTypeKey()
	})
}

// SetTitle sets the "title" field.
func (u *PageUpsertBulk) SetTitle(v string) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateTitle() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateTitle()
	})
}

// SetSlug sets the "slug" field.
func (u *PageUpsertBulk) SetSlug(v string) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateSlug() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateSlug()
	})
}

// SetStatus sets the "status" field.
func (u *PageUpsertBulk) SetStatus(v int16) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *PageUpsertBulk) AddStatus(v int16) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateStatus() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateStatus()
	})
}

// SetContentJSON sets the "content_json" field.
func (u *PageUpsertBulk) SetContentJSON(v json.RawMessage) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetContentJSON(v)
	})
}

// UpdateContentJSON sets the "content_json" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateContentJSON() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateContentJSON()
	})
}

// SetPublishedJSON sets the "published_json" field.
func (u *PageUpsertBulk) SetPublishedJSON(v json.RawMessage) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetPublishedJSON(v)
	})
}

// UpdatePublishedJSON sets the "published_json" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdatePublishedJSON() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdatePublishedJSON()
	})
}

// ClearPublishedJSON clears the value of the "published_json" field.
func (u *PageUpsertBulk) ClearPublishedJSON() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.ClearPublishedJSON()
	})
}

// SetMeta sets the "meta" field.
func (u *PageUpsertBulk) SetMeta(v json.RawMessage) *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.SetMeta(v)
	})
}

// UpdateMeta sets the "meta" field to the value that was provided on create.
func (u *PageUpsertBulk) UpdateMeta() *PageUpsertBulk {
	return u.Update(func(s *PageUpsert) {
		s.UpdateMeta()
	})
}

// Exec executes the query.
func (u *PageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
