// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/page"
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PageUpdate is the builder for updating Page entities.
type PageUpdate struct {
	config
	hooks     []Hook
	mutation  *PageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdate) Where(ps ...predicate.Page) *PageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PageUpdate) SetUpdatedAt(v time.Time) *PageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *PageUpdate) SetShopID(v int) *PageUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *PageUpdate) SetNillableShopID(v *int) *PageUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetTypeKey sets the "type_key" field.
func (_u *PageUpdate) SetTypeKey(v string) *PageUpdate {
	_u.mutation.SetTypeKey(v)
	return _u
}

// SetNillableTypeKey sets the "type_key" field if the given value is not nil.
func (_u *PageUpdate) SetNillableTypeKey(v *string) *PageUpdate {
	if v != nil {
		_u.SetTypeKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PageUpdate) SetTitle(v string) *PageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdate) SetNillableTitle(v *string) *PageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PageUpdate) SetSlug(v string) *PageUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PageUpdate) SetNillableSlug(v *string) *PageUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PageUpdate) SetStatus(v int16) *PageUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PageUpdate) SetNillableStatus(v *int16) *PageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PageUpdate) AddStatus(v int16) *PageUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetContentJSON sets the "content_json" field.
func (_u *PageUpdate) SetContentJSON(v json.RawMessage) *PageUpdate {
	_u.mutation.SetContentJSON(v)
	return _u
}

// AppendContentJSON appends value to the "content_json" field.
func (_u *PageUpdate) AppendContentJSON(v json.RawMessage) *PageUpdate {
	_u.mutation.AppendContentJSON(v)
	return _u
}

// SetPublishedJSON sets the "published_json" field.
func (_u *PageUpdate) SetPublishedJSON(v json.RawMessage) *PageUpdate {
	_u.mutation.SetPublishedJSON(v)
	return _u
}

// AppendPublishedJSON appends value to the "published_json" field.
func (_u *PageUpdate) AppendPublishedJSON(v json.RawMessage) *PageUpdate {
	_u.mutation.AppendPublishedJSON(v)
	return _u
}

// ClearPublishedJSON clears the value of the "published_json" field.
func (_u *PageUpdate) ClearPublishedJSON() *PageUpdate {
	_u.mutation.ClearPublishedJSON()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *PageUpdate) SetMeta(v json.RawMessage) *PageUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// AppendMeta appends value to the "meta" field.
func (_u *PageUpdate) AppendMeta(v json.RawMessage) *PageUpdate {
	_u.mutation.AppendMeta(v)
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *PageUpdate) SetShop(v *Shop) *PageUpdate {
	return _u.SetShopID(v.ID)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdate) Mutation() *PageMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *PageUpdate) ClearShop() *PageUpdate {
	_u.mutation.ClearShop()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := page.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdate) check() error {
	if v, ok := _u.mutation.TypeKey(); ok {
		if err := page.TypeKeyValidator(v); err != nil {
			return &ValidationError{Name: "type_key", err: fmt.Errorf(`ent: validator failed for field "Page.type_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := page.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Page.slug": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.shop"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PageUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PageUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(page.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TypeKey(); ok {
		_spec.SetField(page.FieldTypeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(page.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(page.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(page.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.ContentJSON(); ok {
		_spec.SetField(page.FieldContentJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContentJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldContentJSON, value)
		})
	}
	if value, ok := _u.mutation.PublishedJSON(); ok {
		_spec.SetField(page.FieldPublishedJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublishedJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldPublishedJSON, value)
		})
	}
	if _u.mutation.PublishedJSONCleared() {
		_spec.ClearField(page.FieldPublishedJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(page.FieldMeta, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMeta(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldMeta, value)
		})
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ShopTable,
			Columns: []string{page.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ShopTable,
			Columns: []string{page.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PageUpdateOne is the builder for updating a single Page entity.
type PageUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PageMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PageUpdateOne) SetUpdatedAt(v time.Time) *PageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *PageUpdateOne) SetShopID(v int) *PageUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableShopID(v *int) *PageUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetTypeKey sets the "type_key" field.
func (_u *PageUpdateOne) SetTypeKey(v string) *PageUpdateOne {
	_u.mutation.SetTypeKey(v)
	return _u
}

// SetNillableTypeKey sets the "type_key" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableTypeKey(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetTypeKey(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PageUpdateOne) SetTitle(v string) *PageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableTitle(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *PageUpdateOne) SetSlug(v string) *PageUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableSlug(v *string) *PageUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PageUpdateOne) SetStatus(v int16) *PageUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PageUpdateOne) SetNillableStatus(v *int16) *PageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *PageUpdateOne) AddStatus(v int16) *PageUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetContentJSON sets the "content_json" field.
func (_u *PageUpdateOne) SetContentJSON(v json.RawMessage) *PageUpdateOne {
	_u.mutation.SetContentJSON(v)
	return _u
}

// AppendContentJSON appends value to the "content_json" field.
func (_u *PageUpdateOne) AppendContentJSON(v json.RawMessage) *PageUpdateOne {
	_u.mutation.AppendContentJSON(v)
	return _u
}

// SetPublishedJSON sets the "published_json" field.
func (_u *PageUpdateOne) SetPublishedJSON(v json.RawMessage) *PageUpdateOne {
	_u.mutation.SetPublishedJSON(v)
	return _u
}

// AppendPublishedJSON appends value to the "published_json" field.
func (_u *PageUpdateOne) AppendPublishedJSON(v json.RawMessage) *PageUpdateOne {
	_u.mutation.AppendPublishedJSON(v)
	return _u
}

// ClearPublishedJSON clears the value of the "published_json" field.
func (_u *PageUpdateOne) ClearPublishedJSON() *PageUpdateOne {
	_u.mutation.ClearPublishedJSON()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *PageUpdateOne) SetMeta(v json.RawMessage) *PageUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// AppendMeta appends value to the "meta" field.
func (_u *PageUpdateOne) AppendMeta(v json.RawMessage) *PageUpdateOne {
	_u.mutation.AppendMeta(v)
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *PageUpdateOne) SetShop(v *Shop) *PageUpdateOne {
	return _u.SetShopID(v.ID)
}

// Mutation returns the PageMutation object of the builder.
func (_u *PageUpdateOne) Mutation() *PageMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *PageUpdateOne) ClearShop() *PageUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// Where appends a list predicates to the PageUpdate builder.
func (_u *PageUpdateOne) Where(ps ...predicate.Page) *PageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PageUpdateOne) Select(field string, fields ...string) *PageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Page entity.
func (_u *PageUpdateOne) Save(ctx context.Context) (*Page, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PageUpdateOne) SaveX(ctx context.Context) *Page {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := page.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PageUpdateOne) check() error {
	if v, ok := _u.mutation.TypeKey(); ok {
		if err := page.TypeKeyValidator(v); err != nil {
			return &ValidationError{Name: "type_key", err: fmt.Errorf(`ent: validator failed for field "Page.type_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := page.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Page.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := page.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Page.slug": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Page.shop"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PageUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PageUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PageUpdateOne) sqlSave(ctx context.Context) (_node *Page, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(page.Table, page.Columns, sqlgraph.NewFieldSpec(page.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Page.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, page.FieldID)
		for _, f := range fields {
			if !page.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != page.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(page.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TypeKey(); ok {
		_spec.SetField(page.FieldTypeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(page.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(page.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(page.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(page.FieldStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.ContentJSON(); ok {
		_spec.SetField(page.FieldContentJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedContentJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldContentJSON, value)
		})
	}
	if value, ok := _u.mutation.PublishedJSON(); ok {
		_spec.SetField(page.FieldPublishedJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPublishedJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldPublishedJSON, value)
		})
	}
	if _u.mutation.PublishedJSONCleared() {
		_spec.ClearField(page.FieldPublishedJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(page.FieldMeta, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMeta(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, page.FieldMeta, value)
		})
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ShopTable,
			Columns: []string{page.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   page.ShopTable,
			Columns: []string{page.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Page{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{page.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
