// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/product"
	"ksdevworks/ecommerce/api/internal/ent/productsku"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProductSKU is the model entity for the ProductSKU schema.
type ProductSKU struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID int `json:"shop_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int `json:"product_id,omitempty"`
	// SkuCode holds the value of the "sku_code" field.
	SkuCode string `json:"sku_code,omitempty"`
	// Options holds the value of the "options" field.
	Options json.RawMessage `json:"options,omitempty"`
	// PriceAmount holds the value of the "price_amount" field.
	PriceAmount int64 `json:"price_amount,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// StockQty holds the value of the "stock_qty" field.
	StockQty int32 `json:"stock_qty,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProductSKUQuery when eager-loading is set.
	Edges        ProductSKUEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProductSKUEdges holds the relations/edges for other nodes in the graph.
type ProductSKUEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductSKUEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProductSKUEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProductSKU) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case productsku.FieldOptions:
			values[i] = new([]byte)
		case productsku.FieldIsActive:
			values[i] = new(sql.NullBool)
		case productsku.FieldID, productsku.FieldShopID, productsku.FieldProductID, productsku.FieldPriceAmount, productsku.FieldStockQty:
			values[i] = new(sql.NullInt64)
		case productsku.FieldSkuCode, productsku.FieldCurrency:
			values[i] = new(sql.NullString)
		case productsku.FieldCreatedAt, productsku.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProductSKU fields.
func (_m *ProductSKU) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case productsku.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case productsku.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case productsku.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case productsku.FieldShopID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value.Valid {
				_m.ShopID = int(value.Int64)
			}
		case productsku.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = int(value.Int64)
			}
		case productsku.FieldSkuCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku_code", values[i])
			} else if value.Valid {
				_m.SkuCode = value.String
			}
		case productsku.FieldOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Options); err != nil {
					return fmt.Errorf("unmarshal field options: %w", err)
				}
			}
		case productsku.FieldPriceAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_amount", values[i])
			} else if value.Valid {
				_m.PriceAmount = value.Int64
			}
		case productsku.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case productsku.FieldStockQty:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field stock_qty", values[i])
			} else if value.Valid {
				_m.StockQty = int32(value.Int64)
			}
		case productsku.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProductSKU.
// This includes values selected through modifiers, order, etc.
func (_m *ProductSKU) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the ProductSKU entity.
func (_m *ProductSKU) QueryShop() *ShopQuery {
	return NewProductSKUClient(_m.config).QueryShop(_m)
}

// QueryProduct queries the "product" edge of the ProductSKU entity.
func (_m *ProductSKU) QueryProduct() *ProductQuery {
	return NewProductSKUClient(_m.config).QueryProduct(_m)
}

// Update returns a builder for updating this ProductSKU.
// Note that you need to call ProductSKU.Unwrap() before calling this method if this ProductSKU
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProductSKU) Update() *ProductSKUUpdateOne {
	return NewProductSKUClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProductSKU entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProductSKU) Unwrap() *ProductSKU {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProductSKU is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProductSKU) String() string {
	var builder strings.Builder
	builder.WriteString("ProductSKU(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("sku_code=")
	builder.WriteString(_m.SkuCode)
	builder.WriteString(", ")
	builder.WriteString("options=")
	builder.WriteString(fmt.Sprintf("%v", _m.Options))
	builder.WriteString(", ")
	builder.WriteString("price_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceAmount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("stock_qty=")
	builder.WriteString(fmt.Sprintf("%v", _m.StockQty))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// ProductSKUs is a parsable slice of ProductSKU.
type ProductSKUs []*ProductSKU
