// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"ksdevworks/ecommerce/api/internal/ent/site"
	"ksdevworks/ecommerce/api/internal/ent/siteshop"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// SiteShopQuery is the builder for querying SiteShop entities.
type SiteShopQuery struct {
	config
	ctx        *QueryContext
	order      []siteshop.OrderOption
	inters     []Interceptor
	predicates []predicate.SiteShop
	withSite   *SiteQuery
	withShop   *ShopQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SiteShopQuery builder.
func (_q *SiteShopQuery) Where(ps ...predicate.SiteShop) *SiteShopQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SiteShopQuery) Limit(limit int) *SiteShopQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SiteShopQuery) Offset(offset int) *SiteShopQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SiteShopQuery) Unique(unique bool) *SiteShopQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SiteShopQuery) Order(o ...siteshop.OrderOption) *SiteShopQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySite chains the current query on the "site" edge.
func (_q *SiteShopQuery) QuerySite() *SiteQuery {
	query := (&SiteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(siteshop.Table, siteshop.SiteColumn, selector),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, siteshop.SiteTable, siteshop.SiteColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryShop chains the current query on the "shop" edge.
func (_q *SiteShopQuery) QueryShop() *ShopQuery {
	query := (&ShopClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(siteshop.Table, siteshop.ShopColumn, selector),
			sqlgraph.To(shop.Table, shop.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, siteshop.ShopTable, siteshop.ShopColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SiteShop entity from the query.
// Returns a *NotFoundError when no SiteShop was found.
func (_q *SiteShopQuery) First(ctx context.Context) (*SiteShop, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{siteshop.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SiteShopQuery) FirstX(ctx context.Context) *SiteShop {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single SiteShop entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SiteShop entity is found.
// Returns a *NotFoundError when no SiteShop entities are found.
func (_q *SiteShopQuery) Only(ctx context.Context) (*SiteShop, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{siteshop.Label}
	default:
		return nil, &NotSingularError{siteshop.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SiteShopQuery) OnlyX(ctx context.Context) *SiteShop {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of SiteShops.
func (_q *SiteShopQuery) All(ctx context.Context) ([]*SiteShop, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SiteShop, *SiteShopQuery]()
	return withInterceptors[[]*SiteShop](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SiteShopQuery) AllX(ctx context.Context) []*SiteShop {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *SiteShopQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SiteShopQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SiteShopQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SiteShopQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SiteShopQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SiteShopQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SiteShopQuery) Clone() *SiteShopQuery {
	if _q == nil {
		return nil
	}
	return &SiteShopQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]siteshop.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SiteShop{}, _q.predicates...),
		withSite:   _q.withSite.Clone(),
		withShop:   _q.withShop.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithSite tells the query-builder to eager-load the nodes that are connected to
// the "site" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SiteShopQuery) WithSite(opts ...func(*SiteQuery)) *SiteShopQuery {
	query := (&SiteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSite = query
	return _q
}

// WithShop tells the query-builder to eager-load the nodes that are connected to
// the "shop" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SiteShopQuery) WithShop(opts ...func(*ShopQuery)) *SiteShopQuery {
	query := (&ShopClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withShop = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SiteID int `json:"site_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SiteShop.Query().
//		GroupBy(siteshop.FieldSiteID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SiteShopQuery) GroupBy(field string, fields ...string) *SiteShopGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SiteShopGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = siteshop.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SiteID int `json:"site_id,omitempty"`
//	}
//
//	client.SiteShop.Query().
//		Select(siteshop.FieldSiteID).
//		Scan(ctx, &v)
func (_q *SiteShopQuery) Select(fields ...string) *SiteShopSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SiteShopSelect{SiteShopQuery: _q}
	sbuild.label = siteshop.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SiteShopSelect configured with the given aggregations.
func (_q *SiteShopQuery) Aggregate(fns ...AggregateFunc) *SiteShopSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SiteShopQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !siteshop.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SiteShopQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SiteShop, error) {
	var (
		nodes       = []*SiteShop{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSite != nil,
			_q.withShop != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SiteShop).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SiteShop{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSite; query != nil {
		if err := _q.loadSite(ctx, query, nodes, nil,
			func(n *SiteShop, e *Site) { n.Edges.Site = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withShop; query != nil {
		if err := _q.loadShop(ctx, query, nodes, nil,
			func(n *SiteShop, e *Shop) { n.Edges.Shop = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SiteShopQuery) loadSite(ctx context.Context, query *SiteQuery, nodes []*SiteShop, init func(*SiteShop), assign func(*SiteShop, *Site)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SiteShop)
	for i := range nodes {
		fk := nodes[i].SiteID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(site.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "site_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SiteShopQuery) loadShop(ctx context.Context, query *ShopQuery, nodes []*SiteShop, init func(*SiteShop), assign func(*SiteShop, *Shop)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SiteShop)
	for i := range nodes {
		fk := nodes[i].ShopID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(shop.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shop_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SiteShopQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SiteShopQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(siteshop.Table, siteshop.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withSite != nil {
			_spec.Node.AddColumnOnce(siteshop.FieldSiteID)
		}
		if _q.withShop != nil {
			_spec.Node.AddColumnOnce(siteshop.FieldShopID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SiteShopQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(siteshop.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = siteshop.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SiteShopQuery) ForUpdate(opts ...sql.LockOption) *SiteShopQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SiteShopQuery) ForShare(opts ...sql.LockOption) *SiteShopQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *SiteShopQuery) Modify(modifiers ...func(s *sql.Selector)) *SiteShopSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// SiteShopGroupBy is the group-by builder for SiteShop entities.
type SiteShopGroupBy struct {
	selector
	build *SiteShopQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SiteShopGroupBy) Aggregate(fns ...AggregateFunc) *SiteShopGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SiteShopGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteShopQuery, *SiteShopGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SiteShopGroupBy) sqlScan(ctx context.Context, root *SiteShopQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SiteShopSelect is the builder for selecting fields of SiteShop entities.
type SiteShopSelect struct {
	*SiteShopQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SiteShopSelect) Aggregate(fns ...AggregateFunc) *SiteShopSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SiteShopSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SiteShopQuery, *SiteShopSelect](ctx, _s.SiteShopQuery, _s, _s.inters, v)
}

func (_s *SiteShopSelect) sqlScan(ctx context.Context, root *SiteShopQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *SiteShopSelect) Modify(modifiers ...func(s *sql.Selector)) *SiteShopSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
