// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"ksdevworks/ecommerce/api/internal/ent/site"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdate) SetUpdatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdate) SetDomain(v string) *SiteUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDomain(v *string) *SiteUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSslStatus sets the "ssl_status" field.
func (_u *SiteUpdate) SetSslStatus(v int16) *SiteUpdate {
	_u.mutation.ResetSslStatus()
	_u.mutation.SetSslStatus(v)
	return _u
}

// SetNillableSslStatus sets the "ssl_status" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableSslStatus(v *int16) *SiteUpdate {
	if v != nil {
		_u.SetSslStatus(*v)
	}
	return _u
}

// AddSslStatus adds value to the "ssl_status" field.
func (_u *SiteUpdate) AddSslStatus(v int16) *SiteUpdate {
	_u.mutation.AddSslStatus(v)
	return _u
}

// SetMeta sets the "meta" field.
func (_u *SiteUpdate) SetMeta(v json.RawMessage) *SiteUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// AppendMeta appends value to the "meta" field.
func (_u *SiteUpdate) AppendMeta(v json.RawMessage) *SiteUpdate {
	_u.mutation.AppendMeta(v)
	return _u
}

// AddShopIDs adds the "shops" edge to the Shop entity by IDs.
func (_u *SiteUpdate) AddShopIDs(ids ...int) *SiteUpdate {
	_u.mutation.AddShopIDs(ids...)
	return _u
}

// AddShops adds the "shops" edges to the Shop entity.
func (_u *SiteUpdate) AddShops(v ...*Shop) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShopIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearShops clears all "shops" edges to the Shop entity.
func (_u *SiteUpdate) ClearShops() *SiteUpdate {
	_u.mutation.ClearShops()
	return _u
}

// RemoveShopIDs removes the "shops" edge to Shop entities by IDs.
func (_u *SiteUpdate) RemoveShopIDs(ids ...int) *SiteUpdate {
	_u.mutation.RemoveShopIDs(ids...)
	return _u
}

// RemoveShops removes "shops" edges to Shop entities.
func (_u *SiteUpdate) RemoveShops(v ...*Shop) *SiteUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShopIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := site.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Site.domain": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.SslStatus(); ok {
		_spec.SetField(site.FieldSslStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSslStatus(); ok {
		_spec.AddField(site.FieldSslStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(site.FieldMeta, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMeta(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, site.FieldMeta, value)
		})
	}
	if _u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShopsIDs(); len(nodes) > 0 && !_u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SiteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdateOne) SetUpdatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdateOne) SetDomain(v string) *SiteUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDomain(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetSslStatus sets the "ssl_status" field.
func (_u *SiteUpdateOne) SetSslStatus(v int16) *SiteUpdateOne {
	_u.mutation.ResetSslStatus()
	_u.mutation.SetSslStatus(v)
	return _u
}

// SetNillableSslStatus sets the "ssl_status" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableSslStatus(v *int16) *SiteUpdateOne {
	if v != nil {
		_u.SetSslStatus(*v)
	}
	return _u
}

// AddSslStatus adds value to the "ssl_status" field.
func (_u *SiteUpdateOne) AddSslStatus(v int16) *SiteUpdateOne {
	_u.mutation.AddSslStatus(v)
	return _u
}

// SetMeta sets the "meta" field.
func (_u *SiteUpdateOne) SetMeta(v json.RawMessage) *SiteUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// AppendMeta appends value to the "meta" field.
func (_u *SiteUpdateOne) AppendMeta(v json.RawMessage) *SiteUpdateOne {
	_u.mutation.AppendMeta(v)
	return _u
}

// AddShopIDs adds the "shops" edge to the Shop entity by IDs.
func (_u *SiteUpdateOne) AddShopIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.AddShopIDs(ids...)
	return _u
}

// AddShops adds the "shops" edges to the Shop entity.
func (_u *SiteUpdateOne) AddShops(v ...*Shop) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShopIDs(ids...)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearShops clears all "shops" edges to the Shop entity.
func (_u *SiteUpdateOne) ClearShops() *SiteUpdateOne {
	_u.mutation.ClearShops()
	return _u
}

// RemoveShopIDs removes the "shops" edge to Shop entities by IDs.
func (_u *SiteUpdateOne) RemoveShopIDs(ids ...int) *SiteUpdateOne {
	_u.mutation.RemoveShopIDs(ids...)
	return _u
}

// RemoveShops removes "shops" edges to Shop entities.
func (_u *SiteUpdateOne) RemoveShops(v ...*Shop) *SiteUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShopIDs(ids...)
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SiteUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := site.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Site.domain": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SiteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SiteUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.SslStatus(); ok {
		_spec.SetField(site.FieldSslStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedSslStatus(); ok {
		_spec.AddField(site.FieldSslStatus, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(site.FieldMeta, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMeta(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, site.FieldMeta, value)
		})
	}
	if _u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShopsIDs(); len(nodes) > 0 && !_u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   site.ShopsTable,
			Columns: site.ShopsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SiteShopCreate{config: _u.config, mutation: newSiteShopMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
