// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"ksdevworks/ecommerce/api/internal/ent/theme"
	"ksdevworks/ecommerce/api/internal/ent/themepage"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ThemeCreate is the builder for creating a Theme entity.
type ThemeCreate struct {
	config
	mutation *ThemeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThemeCreate) SetCreatedAt(v time.Time) *ThemeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableCreatedAt(v *time.Time) *ThemeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ThemeCreate) SetUpdatedAt(v time.Time) *ThemeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableUpdatedAt(v *time.Time) *ThemeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *ThemeCreate) SetCode(v string) *ThemeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ThemeCreate) SetName(v string) *ThemeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLayoutKey sets the "layout_key" field.
func (_c *ThemeCreate) SetLayoutKey(v string) *ThemeCreate {
	_c.mutation.SetLayoutKey(v)
	return _c
}

// SetConfigSchema sets the "config_schema" field.
func (_c *ThemeCreate) SetConfigSchema(v json.RawMessage) *ThemeCreate {
	_c.mutation.SetConfigSchema(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ThemeCreate) SetIsActive(v bool) *ThemeCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableIsActive(v *bool) *ThemeCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// AddPageIDs adds the "pages" edge to the ThemePage entity by IDs.
func (_c *ThemeCreate) AddPageIDs(ids ...int) *ThemeCreate {
	_c.mutation.AddPageIDs(ids...)
	return _c
}

// AddPages adds the "pages" edges to the ThemePage entity.
func (_c *ThemeCreate) AddPages(v ...*ThemePage) *ThemeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPageIDs(ids...)
}

// AddShopIDs adds the "shops" edge to the Shop entity by IDs.
func (_c *ThemeCreate) AddShopIDs(ids ...int) *ThemeCreate {
	_c.mutation.AddShopIDs(ids...)
	return _c
}

// AddShops adds the "shops" edges to the Shop entity.
func (_c *ThemeCreate) AddShops(v ...*Shop) *ThemeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShopIDs(ids...)
}

// Mutation returns the ThemeMutation object of the builder.
func (_c *ThemeCreate) Mutation() *ThemeMutation {
	return _c.mutation
}

// Save creates the Theme in the database.
func (_c *ThemeCreate) Save(ctx context.Context) (*Theme, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThemeCreate) SaveX(ctx context.Context) *Theme {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThemeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThemeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThemeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := theme.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := theme.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ConfigSchema(); !ok {
		v := theme.DefaultConfigSchema
		_c.mutation.SetConfigSchema(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := theme.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThemeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Theme.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Theme.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Theme.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := theme.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Theme.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Theme.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LayoutKey(); !ok {
		return &ValidationError{Name: "layout_key", err: errors.New(`ent: missing required field "Theme.layout_key"`)}
	}
	if v, ok := _c.mutation.LayoutKey(); ok {
		if err := theme.LayoutKeyValidator(v); err != nil {
			return &ValidationError{Name: "layout_key", err: fmt.Errorf(`ent: validator failed for field "Theme.layout_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConfigSchema(); !ok {
		return &ValidationError{Name: "config_schema", err: errors.New(`ent: missing required field "Theme.config_schema"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Theme.is_active"`)}
	}
	return nil
}

func (_c *ThemeCreate) sqlSave(ctx context.Context) (*Theme, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThemeCreate) createSpec() (*Theme, *sqlgraph.CreateSpec) {
	var (
		_node = &Theme{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(theme.Table, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(theme.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(theme.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LayoutKey(); ok {
		_spec.SetField(theme.FieldLayoutKey, field.TypeString, value)
		_node.LayoutKey = value
	}
	if value, ok := _c.mutation.ConfigSchema(); ok {
		_spec.SetField(theme.FieldConfigSchema, field.TypeJSON, value)
		_node.ConfigSchema = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(theme.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.PagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Theme.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThemeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ThemeCreate) OnConflict(opts ...sql.ConflictOption) *ThemeUpsertOne {
	_c.conflict = opts
	return &ThemeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Theme.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThemeCreate) OnConflictColumns(columns ...string) *ThemeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThemeUpsertOne{
		create: _c,
	}
}

type (
	// ThemeUpsertOne is the builder for "upsert"-ing
	//  one Theme node.
	ThemeUpsertOne struct {
		create *ThemeCreate
	}

	// ThemeUpsert is the "OnConflict" setter.
	ThemeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ThemeUpsert) SetUpdatedAt(v time.Time) *ThemeUpsert {
	u.Set(theme.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateUpdatedAt() *ThemeUpsert {
	u.SetExcluded(theme.FieldUpdatedAt)
	return u
}

// SetCode sets the "code" field.
func (u *ThemeUpsert) SetCode(v string) *ThemeUpsert {
	u.Set(theme.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateCode() *ThemeUpsert {
	u.SetExcluded(theme.FieldCode)
	return u
}

// SetName sets the "name" field.
func (u *ThemeUpsert) SetName(v string) *ThemeUpsert {
	u.Set(theme.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateName() *ThemeUpsert {
	u.SetExcluded(theme.FieldName)
	return u
}

// SetLayoutKey sets the "layout_key" field.
func (u *ThemeUpsert) SetLayoutKey(v string) *ThemeUpsert {
	u.Set(theme.FieldLayoutKey, v)
	return u
}

// UpdateLayoutKey sets the "layout_key" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateLayoutKey() *ThemeUpsert {
	u.SetExcluded(theme.FieldLayoutKey)
	return u
}

// SetConfigSchema sets the "config_schema" field.
func (u *ThemeUpsert) SetConfigSchema(v json.RawMessage) *ThemeUpsert {
	u.Set(theme.FieldConfigSchema, v)
	return u
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateConfigSchema() *ThemeUpsert {
	u.SetExcluded(theme.FieldConfigSchema)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *ThemeUpsert) SetIsActive(v bool) *ThemeUpsert {
	u.Set(theme.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ThemeUpsert) UpdateIsActive() *ThemeUpsert {
	u.SetExcluded(theme.FieldIsActive)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Theme.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ThemeUpsertOne) UpdateNewValues() *ThemeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(theme.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Theme.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ThemeUpsertOne) Ignore() *ThemeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThemeUpsertOne) DoNothing() *ThemeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThemeCreate.OnConflict
// documentation for more info.
func (u *ThemeUpsertOne) Update(set func(*ThemeUpsert)) *ThemeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThemeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ThemeUpsertOne) SetUpdatedAt(v time.Time) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateUpdatedAt() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *ThemeUpsertOne) SetCode(v string) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateCode() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *ThemeUpsertOne) SetName(v string) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateName() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateName()
	})
}

// SetLayoutKey sets the "layout_key" field.
func (u *ThemeUpsertOne) SetLayoutKey(v string) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetLayoutKey(v)
	})
}

// UpdateLayoutKey sets the "layout_key" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateLayoutKey() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateLayoutKey()
	})
}

// SetConfigSchema sets the "config_schema" field.
func (u *ThemeUpsertOne) SetConfigSchema(v json.RawMessage) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetConfigSchema(v)
	})
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateConfigSchema() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateConfigSchema()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ThemeUpsertOne) SetIsActive(v bool) *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ThemeUpsertOne) UpdateIsActive() *ThemeUpsertOne {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *ThemeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThemeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThemeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ThemeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ThemeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ThemeCreateBulk is the builder for creating many Theme entities in bulk.
type ThemeCreateBulk struct {
	config
	err      error
	builders []*ThemeCreate
	conflict []sql.ConflictOption
}

// Save creates the Theme entities in the database.
func (_c *ThemeCreateBulk) Save(ctx context.Context) ([]*Theme, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Theme, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThemeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThemeCreateBulk) SaveX(ctx context.Context) []*Theme {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThemeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThemeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Theme.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ThemeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ThemeCreateBulk) OnConflict(opts ...sql.ConflictOption) *ThemeUpsertBulk {
	_c.conflict = opts
	return &ThemeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Theme.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ThemeCreateBulk) OnConflictColumns(columns ...string) *ThemeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ThemeUpsertBulk{
		create: _c,
	}
}

// ThemeUpsertBulk is the builder for "upsert"-ing
// a bulk of Theme nodes.
type ThemeUpsertBulk struct {
	create *ThemeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Theme.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ThemeUpsertBulk) UpdateNewValues() *ThemeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(theme.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Theme.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ThemeUpsertBulk) Ignore() *ThemeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ThemeUpsertBulk) DoNothing() *ThemeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ThemeCreateBulk.OnConflict
// documentation for more info.
func (u *ThemeUpsertBulk) Update(set func(*ThemeUpsert)) *ThemeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ThemeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ThemeUpsertBulk) SetUpdatedAt(v time.Time) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateUpdatedAt() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCode sets the "code" field.
func (u *ThemeUpsertBulk) SetCode(v string) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateCode() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateCode()
	})
}

// SetName sets the "name" field.
func (u *ThemeUpsertBulk) SetName(v string) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateName() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateName()
	})
}

// SetLayoutKey sets the "layout_key" field.
func (u *ThemeUpsertBulk) SetLayoutKey(v string) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetLayoutKey(v)
	})
}

// UpdateLayoutKey sets the "layout_key" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateLayoutKey() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateLayoutKey()
	})
}

// SetConfigSchema sets the "config_schema" field.
func (u *ThemeUpsertBulk) SetConfigSchema(v json.RawMessage) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetConfigSchema(v)
	})
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateConfigSchema() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateConfigSchema()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ThemeUpsertBulk) SetIsActive(v bool) *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ThemeUpsertBulk) UpdateIsActive() *ThemeUpsertBulk {
	return u.Update(func(s *ThemeUpsert) {
		s.UpdateIsActive()
	})
}

// Exec executes the query.
func (u *ThemeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ThemeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ThemeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ThemeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
