// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"ksdevworks/ecommerce/api/internal/ent/shop"
	"ksdevworks/ecommerce/api/internal/ent/theme"
	"ksdevworks/ecommerce/api/internal/ent/themepage"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ThemeUpdate is the builder for updating Theme entities.
type ThemeUpdate struct {
	config
	hooks     []Hook
	mutation  *ThemeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ThemeUpdate builder.
func (_u *ThemeUpdate) Where(ps ...predicate.Theme) *ThemeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ThemeUpdate) SetUpdatedAt(v time.Time) *ThemeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *ThemeUpdate) SetCode(v string) *ThemeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableCode(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ThemeUpdate) SetName(v string) *ThemeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableName(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLayoutKey sets the "layout_key" field.
func (_u *ThemeUpdate) SetLayoutKey(v string) *ThemeUpdate {
	_u.mutation.SetLayoutKey(v)
	return _u
}

// SetNillableLayoutKey sets the "layout_key" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableLayoutKey(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetLayoutKey(*v)
	}
	return _u
}

// SetConfigSchema sets the "config_schema" field.
func (_u *ThemeUpdate) SetConfigSchema(v json.RawMessage) *ThemeUpdate {
	_u.mutation.SetConfigSchema(v)
	return _u
}

// AppendConfigSchema appends value to the "config_schema" field.
func (_u *ThemeUpdate) AppendConfigSchema(v json.RawMessage) *ThemeUpdate {
	_u.mutation.AppendConfigSchema(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ThemeUpdate) SetIsActive(v bool) *ThemeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableIsActive(v *bool) *ThemeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddPageIDs adds the "pages" edge to the ThemePage entity by IDs.
func (_u *ThemeUpdate) AddPageIDs(ids ...int) *ThemeUpdate {
	_u.mutation.AddPageIDs(ids...)
	return _u
}

// AddPages adds the "pages" edges to the ThemePage entity.
func (_u *ThemeUpdate) AddPages(v ...*ThemePage) *ThemeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPageIDs(ids...)
}

// AddShopIDs adds the "shops" edge to the Shop entity by IDs.
func (_u *ThemeUpdate) AddShopIDs(ids ...int) *ThemeUpdate {
	_u.mutation.AddShopIDs(ids...)
	return _u
}

// AddShops adds the "shops" edges to the Shop entity.
func (_u *ThemeUpdate) AddShops(v ...*Shop) *ThemeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShopIDs(ids...)
}

// Mutation returns the ThemeMutation object of the builder.
func (_u *ThemeUpdate) Mutation() *ThemeMutation {
	return _u.mutation
}

// ClearPages clears all "pages" edges to the ThemePage entity.
func (_u *ThemeUpdate) ClearPages() *ThemeUpdate {
	_u.mutation.ClearPages()
	return _u
}

// RemovePageIDs removes the "pages" edge to ThemePage entities by IDs.
func (_u *ThemeUpdate) RemovePageIDs(ids ...int) *ThemeUpdate {
	_u.mutation.RemovePageIDs(ids...)
	return _u
}

// RemovePages removes "pages" edges to ThemePage entities.
func (_u *ThemeUpdate) RemovePages(v ...*ThemePage) *ThemeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePageIDs(ids...)
}

// ClearShops clears all "shops" edges to the Shop entity.
func (_u *ThemeUpdate) ClearShops() *ThemeUpdate {
	_u.mutation.ClearShops()
	return _u
}

// RemoveShopIDs removes the "shops" edge to Shop entities by IDs.
func (_u *ThemeUpdate) RemoveShopIDs(ids ...int) *ThemeUpdate {
	_u.mutation.RemoveShopIDs(ids...)
	return _u
}

// RemoveShops removes "shops" edges to Shop entities.
func (_u *ThemeUpdate) RemoveShops(v ...*Shop) *ThemeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShopIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ThemeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThemeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ThemeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThemeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ThemeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theme.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThemeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := theme.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Theme.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LayoutKey(); ok {
		if err := theme.LayoutKeyValidator(v); err != nil {
			return &ValidationError{Name: "layout_key", err: fmt.Errorf(`ent: validator failed for field "Theme.layout_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThemeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThemeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThemeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theme.Table, theme.Columns, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(theme.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LayoutKey(); ok {
		_spec.SetField(theme.FieldLayoutKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigSchema(); ok {
		_spec.SetField(theme.FieldConfigSchema, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigSchema(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, theme.FieldConfigSchema, value)
		})
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(theme.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.PagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPagesIDs(); len(nodes) > 0 && !_u.mutation.PagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShopsIDs(); len(nodes) > 0 && !_u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ThemeUpdateOne is the builder for updating a single Theme entity.
type ThemeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ThemeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ThemeUpdateOne) SetUpdatedAt(v time.Time) *ThemeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCode sets the "code" field.
func (_u *ThemeUpdateOne) SetCode(v string) *ThemeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableCode(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ThemeUpdateOne) SetName(v string) *ThemeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableName(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLayoutKey sets the "layout_key" field.
func (_u *ThemeUpdateOne) SetLayoutKey(v string) *ThemeUpdateOne {
	_u.mutation.SetLayoutKey(v)
	return _u
}

// SetNillableLayoutKey sets the "layout_key" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableLayoutKey(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetLayoutKey(*v)
	}
	return _u
}

// SetConfigSchema sets the "config_schema" field.
func (_u *ThemeUpdateOne) SetConfigSchema(v json.RawMessage) *ThemeUpdateOne {
	_u.mutation.SetConfigSchema(v)
	return _u
}

// AppendConfigSchema appends value to the "config_schema" field.
func (_u *ThemeUpdateOne) AppendConfigSchema(v json.RawMessage) *ThemeUpdateOne {
	_u.mutation.AppendConfigSchema(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ThemeUpdateOne) SetIsActive(v bool) *ThemeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableIsActive(v *bool) *ThemeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// AddPageIDs adds the "pages" edge to the ThemePage entity by IDs.
func (_u *ThemeUpdateOne) AddPageIDs(ids ...int) *ThemeUpdateOne {
	_u.mutation.AddPageIDs(ids...)
	return _u
}

// AddPages adds the "pages" edges to the ThemePage entity.
func (_u *ThemeUpdateOne) AddPages(v ...*ThemePage) *ThemeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPageIDs(ids...)
}

// AddShopIDs adds the "shops" edge to the Shop entity by IDs.
func (_u *ThemeUpdateOne) AddShopIDs(ids ...int) *ThemeUpdateOne {
	_u.mutation.AddShopIDs(ids...)
	return _u
}

// AddShops adds the "shops" edges to the Shop entity.
func (_u *ThemeUpdateOne) AddShops(v ...*Shop) *ThemeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddShopIDs(ids...)
}

// Mutation returns the ThemeMutation object of the builder.
func (_u *ThemeUpdateOne) Mutation() *ThemeMutation {
	return _u.mutation
}

// ClearPages clears all "pages" edges to the ThemePage entity.
func (_u *ThemeUpdateOne) ClearPages() *ThemeUpdateOne {
	_u.mutation.ClearPages()
	return _u
}

// RemovePageIDs removes the "pages" edge to ThemePage entities by IDs.
func (_u *ThemeUpdateOne) RemovePageIDs(ids ...int) *ThemeUpdateOne {
	_u.mutation.RemovePageIDs(ids...)
	return _u
}

// RemovePages removes "pages" edges to ThemePage entities.
func (_u *ThemeUpdateOne) RemovePages(v ...*ThemePage) *ThemeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePageIDs(ids...)
}

// ClearShops clears all "shops" edges to the Shop entity.
func (_u *ThemeUpdateOne) ClearShops() *ThemeUpdateOne {
	_u.mutation.ClearShops()
	return _u
}

// RemoveShopIDs removes the "shops" edge to Shop entities by IDs.
func (_u *ThemeUpdateOne) RemoveShopIDs(ids ...int) *ThemeUpdateOne {
	_u.mutation.RemoveShopIDs(ids...)
	return _u
}

// RemoveShops removes "shops" edges to Shop entities.
func (_u *ThemeUpdateOne) RemoveShops(v ...*Shop) *ThemeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveShopIDs(ids...)
}

// Where appends a list predicates to the ThemeUpdate builder.
func (_u *ThemeUpdateOne) Where(ps ...predicate.Theme) *ThemeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ThemeUpdateOne) Select(field string, fields ...string) *ThemeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Theme entity.
func (_u *ThemeUpdateOne) Save(ctx context.Context) (*Theme, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThemeUpdateOne) SaveX(ctx context.Context) *Theme {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ThemeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThemeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ThemeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theme.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThemeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := theme.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Theme.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LayoutKey(); ok {
		if err := theme.LayoutKeyValidator(v); err != nil {
			return &ValidationError{Name: "layout_key", err: fmt.Errorf(`ent: validator failed for field "Theme.layout_key": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ThemeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ThemeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ThemeUpdateOne) sqlSave(ctx context.Context) (_node *Theme, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theme.Table, theme.Columns, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Theme.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theme.FieldID)
		for _, f := range fields {
			if !theme.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != theme.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(theme.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LayoutKey(); ok {
		_spec.SetField(theme.FieldLayoutKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigSchema(); ok {
		_spec.SetField(theme.FieldConfigSchema, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigSchema(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, theme.FieldConfigSchema, value)
		})
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(theme.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.PagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPagesIDs(); len(nodes) > 0 && !_u.mutation.PagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   theme.PagesTable,
			Columns: []string{theme.PagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(themepage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedShopsIDs(); len(nodes) > 0 && !_u.mutation.ShopsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   theme.ShopsTable,
			Columns: []string{theme.ShopsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Theme{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
