// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/theme"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Theme is the model entity for the Theme schema.
type Theme struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// LayoutKey holds the value of the "layout_key" field.
	LayoutKey string `json:"layout_key,omitempty"`
	// ConfigSchema holds the value of the "config_schema" field.
	ConfigSchema json.RawMessage `json:"config_schema,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThemeQuery when eager-loading is set.
	Edges        ThemeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ThemeEdges holds the relations/edges for other nodes in the graph.
type ThemeEdges struct {
	// Pages holds the value of the pages edge.
	Pages []*ThemePage `json:"pages,omitempty"`
	// Shops holds the value of the shops edge.
	Shops []*Shop `json:"shops,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PagesOrErr returns the Pages value or an error if the edge
// was not loaded in eager-loading.
func (e ThemeEdges) PagesOrErr() ([]*ThemePage, error) {
	if e.loadedTypes[0] {
		return e.Pages, nil
	}
	return nil, &NotLoadedError{edge: "pages"}
}

// ShopsOrErr returns the Shops value or an error if the edge
// was not loaded in eager-loading.
func (e ThemeEdges) ShopsOrErr() ([]*Shop, error) {
	if e.loadedTypes[1] {
		return e.Shops, nil
	}
	return nil, &NotLoadedError{edge: "shops"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Theme) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case theme.FieldConfigSchema:
			values[i] = new([]byte)
		case theme.FieldIsActive:
			values[i] = new(sql.NullBool)
		case theme.FieldID:
			values[i] = new(sql.NullInt64)
		case theme.FieldCode, theme.FieldName, theme.FieldLayoutKey:
			values[i] = new(sql.NullString)
		case theme.FieldCreatedAt, theme.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Theme fields.
func (_m *Theme) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case theme.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case theme.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case theme.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case theme.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case theme.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case theme.FieldLayoutKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field layout_key", values[i])
			} else if value.Valid {
				_m.LayoutKey = value.String
			}
		case theme.FieldConfigSchema:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_schema", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigSchema); err != nil {
					return fmt.Errorf("unmarshal field config_schema: %w", err)
				}
			}
		case theme.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Theme.
// This includes values selected through modifiers, order, etc.
func (_m *Theme) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPages queries the "pages" edge of the Theme entity.
func (_m *Theme) QueryPages() *ThemePageQuery {
	return NewThemeClient(_m.config).QueryPages(_m)
}

// QueryShops queries the "shops" edge of the Theme entity.
func (_m *Theme) QueryShops() *ShopQuery {
	return NewThemeClient(_m.config).QueryShops(_m)
}

// Update returns a builder for updating this Theme.
// Note that you need to call Theme.Unwrap() before calling this method if this Theme
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Theme) Update() *ThemeUpdateOne {
	return NewThemeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Theme entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Theme) Unwrap() *Theme {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Theme is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Theme) String() string {
	var builder strings.Builder
	builder.WriteString("Theme(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("layout_key=")
	builder.WriteString(_m.LayoutKey)
	builder.WriteString(", ")
	builder.WriteString("config_schema=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigSchema))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteByte(')')
	return builder.String()
}

// Themes is a parsable slice of Theme.
type Themes []*Theme
