// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"ksdevworks/ecommerce/api/internal/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Status holds the value of the "status" field.
	Status int16 `json:"status,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta json.RawMessage `json:"meta,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// ShopUsers holds the value of the shop_users edge.
	ShopUsers []*ShopUser `json:"shop_users,omitempty"`
	// RoleUsers holds the value of the role_users edge.
	RoleUsers []*RoleUser `json:"role_users,omitempty"`
	// UserPermissions holds the value of the user_permissions edge.
	UserPermissions []*UserPermission `json:"user_permissions,omitempty"`
	// RefreshTokens holds the value of the refresh_tokens edge.
	RefreshTokens []*UserRefreshToken `json:"refresh_tokens,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ShopUsersOrErr returns the ShopUsers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ShopUsersOrErr() ([]*ShopUser, error) {
	if e.loadedTypes[0] {
		return e.ShopUsers, nil
	}
	return nil, &NotLoadedError{edge: "shop_users"}
}

// RoleUsersOrErr returns the RoleUsers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RoleUsersOrErr() ([]*RoleUser, error) {
	if e.loadedTypes[1] {
		return e.RoleUsers, nil
	}
	return nil, &NotLoadedError{edge: "role_users"}
}

// UserPermissionsOrErr returns the UserPermissions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserPermissionsOrErr() ([]*UserPermission, error) {
	if e.loadedTypes[2] {
		return e.UserPermissions, nil
	}
	return nil, &NotLoadedError{edge: "user_permissions"}
}

// RefreshTokensOrErr returns the RefreshTokens value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RefreshTokensOrErr() ([]*UserRefreshToken, error) {
	if e.loadedTypes[3] {
		return e.RefreshTokens, nil
	}
	return nil, &NotLoadedError{edge: "refresh_tokens"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldMeta:
			values[i] = new([]byte)
		case user.FieldID, user.FieldStatus:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int16(value.Int64)
			}
		case user.FieldMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Meta); err != nil {
					return fmt.Errorf("unmarshal field meta: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShopUsers queries the "shop_users" edge of the User entity.
func (_m *User) QueryShopUsers() *ShopUserQuery {
	return NewUserClient(_m.config).QueryShopUsers(_m)
}

// QueryRoleUsers queries the "role_users" edge of the User entity.
func (_m *User) QueryRoleUsers() *RoleUserQuery {
	return NewUserClient(_m.config).QueryRoleUsers(_m)
}

// QueryUserPermissions queries the "user_permissions" edge of the User entity.
func (_m *User) QueryUserPermissions() *UserPermissionQuery {
	return NewUserClient(_m.config).QueryUserPermissions(_m)
}

// QueryRefreshTokens queries the "refresh_tokens" edge of the User entity.
func (_m *User) QueryRefreshTokens() *UserRefreshTokenQuery {
	return NewUserClient(_m.config).QueryRefreshTokens(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("meta=")
	builder.WriteString(fmt.Sprintf("%v", _m.Meta))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
