// Generates TypeScript types from the starter theme JSON Schemas (task 8.4).
// Source of truth: /api/internal/seed/schemas/starter/*.json — the same files
// the seed loads into the themes tables, so backend validation, hydration and
// frontend props all derive from one definition (design D6).
//
//   npm run gen:types   → themes/starter/schema-types.ts (committed)
import { compile } from "json-schema-to-typescript";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaDir = join(here, "..", "..", "api", "internal", "seed", "schemas", "starter");
const outFile = join(here, "..", "themes", "starter", "schema-types.ts");

const compileOpts = {
  bannerComment: "",
  additionalProperties: false,
  style: { singleQuote: false },
};

const pascal = (s) =>
  s
    .split(/[_-]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");

async function main() {
  const config = JSON.parse(await readFile(join(schemaDir, "config_schema.json"), "utf8"));
  const sections = JSON.parse(await readFile(join(schemaDir, "sections_defs.json"), "utf8"));

  let out =
    "// AUTO-GENERATED by scripts/gen-types.mjs from api/internal/seed/schemas/starter/*.json\n" +
    "// Do not edit by hand — run `npm run gen:types` after changing the schemas.\n\n";

  out += await compile({ ...config, title: "StarterConfig" }, "StarterConfig", compileOpts);
  out += "\n";

  const names = [];
  for (const [key, schema] of Object.entries(sections)) {
    const name = `${pascal(key)}Section`;
    names.push(name);
    out += await compile({ ...schema, title: name }, name, compileOpts);
    out += "\n";
  }
  out += `export type StarterSection = ${names.join(" | ")};\n`;

  await writeFile(outFile, out, "utf8");
  console.log(`wrote ${outFile}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
