// Code generated by ent, DO NOT EDIT.

package cartitem

import (
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldShopID, v))
}

// CartID applies equality check predicate on the "cart_id" field. It's identical to CartIDEQ.
func CartID(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCartID, v))
}

// SkuID applies equality check predicate on the "sku_id" field. It's identical to SkuIDEQ.
func SkuID(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldSkuID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldQuantity, v))
}

// PriceAmount applies equality check predicate on the "price_amount" field. It's identical to PriceAmountEQ.
func PriceAmount(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldPriceAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCurrency, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldShopID, vs...))
}

// CartIDEQ applies the EQ predicate on the "cart_id" field.
func CartIDEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCartID, v))
}

// CartIDNEQ applies the NEQ predicate on the "cart_id" field.
func CartIDNEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldCartID, v))
}

// CartIDIn applies the In predicate on the "cart_id" field.
func CartIDIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldCartID, vs...))
}

// CartIDNotIn applies the NotIn predicate on the "cart_id" field.
func CartIDNotIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldCartID, vs...))
}

// SkuIDEQ applies the EQ predicate on the "sku_id" field.
func SkuIDEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldSkuID, v))
}

// SkuIDNEQ applies the NEQ predicate on the "sku_id" field.
func SkuIDNEQ(v int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldSkuID, v))
}

// SkuIDIn applies the In predicate on the "sku_id" field.
func SkuIDIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldSkuID, vs...))
}

// SkuIDNotIn applies the NotIn predicate on the "sku_id" field.
func SkuIDNotIn(vs ...int) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldSkuID, vs...))
}

// SkuIDIsNil applies the IsNil predicate on the "sku_id" field.
func SkuIDIsNil() predicate.CartItem {
	return predicate.CartItem(sql.FieldIsNull(FieldSkuID))
}

// SkuIDNotNil applies the NotNil predicate on the "sku_id" field.
func SkuIDNotNil() predicate.CartItem {
	return predicate.CartItem(sql.FieldNotNull(FieldSkuID))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int32) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldQuantity, v))
}

// PriceAmountEQ applies the EQ predicate on the "price_amount" field.
func PriceAmountEQ(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldPriceAmount, v))
}

// PriceAmountNEQ applies the NEQ predicate on the "price_amount" field.
func PriceAmountNEQ(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldPriceAmount, v))
}

// PriceAmountIn applies the In predicate on the "price_amount" field.
func PriceAmountIn(vs ...int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldPriceAmount, vs...))
}

// PriceAmountNotIn applies the NotIn predicate on the "price_amount" field.
func PriceAmountNotIn(vs ...int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldPriceAmount, vs...))
}

// PriceAmountGT applies the GT predicate on the "price_amount" field.
func PriceAmountGT(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldPriceAmount, v))
}

// PriceAmountGTE applies the GTE predicate on the "price_amount" field.
func PriceAmountGTE(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldPriceAmount, v))
}

// PriceAmountLT applies the LT predicate on the "price_amount" field.
func PriceAmountLT(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldPriceAmount, v))
}

// PriceAmountLTE applies the LTE predicate on the "price_amount" field.
func PriceAmountLTE(v int64) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldPriceAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.CartItem {
	return predicate.CartItem(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.CartItem {
	return predicate.CartItem(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.CartItem {
	return predicate.CartItem(sql.FieldContainsFold(FieldCurrency, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCart applies the HasEdge predicate on the "cart" edge.
func HasCart() predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CartTable, CartColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCartWith applies the HasEdge predicate on the "cart" edge with a given conditions (other predicates).
func HasCartWith(preds ...predicate.Cart) predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := newCartStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSku applies the HasEdge predicate on the "sku" edge.
func HasSku() predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SkuTable, SkuColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSkuWith applies the HasEdge predicate on the "sku" edge with a given conditions (other predicates).
func HasSkuWith(preds ...predicate.ProductSKU) predicate.CartItem {
	return predicate.CartItem(func(s *sql.Selector) {
		step := newSkuStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CartItem) predicate.CartItem {
	return predicate.CartItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CartItem) predicate.CartItem {
	return predicate.CartItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CartItem) predicate.CartItem {
	return predicate.CartItem(sql.NotPredicates(p))
}
