// Code generated by ent, DO NOT EDIT.

package pointtransaction

import (
	"ksdevworks/ecommerce/api/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldShopID, v))
}

// ShopMemberID applies equality check predicate on the "shop_member_id" field. It's identical to ShopMemberIDEQ.
func ShopMemberID(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldShopMemberID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldOrderID, v))
}

// PointsDelta applies equality check predicate on the "points_delta" field. It's identical to PointsDeltaEQ.
func PointsDelta(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldPointsDelta, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldKind, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldShopID, vs...))
}

// ShopMemberIDEQ applies the EQ predicate on the "shop_member_id" field.
func ShopMemberIDEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldShopMemberID, v))
}

// ShopMemberIDNEQ applies the NEQ predicate on the "shop_member_id" field.
func ShopMemberIDNEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldShopMemberID, v))
}

// ShopMemberIDIn applies the In predicate on the "shop_member_id" field.
func ShopMemberIDIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldShopMemberID, vs...))
}

// ShopMemberIDNotIn applies the NotIn predicate on the "shop_member_id" field.
func ShopMemberIDNotIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldShopMemberID, vs...))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDIsNil applies the IsNil predicate on the "order_id" field.
func OrderIDIsNil() predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIsNull(FieldOrderID))
}

// OrderIDNotNil applies the NotNil predicate on the "order_id" field.
func OrderIDNotNil() predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotNull(FieldOrderID))
}

// PointsDeltaEQ applies the EQ predicate on the "points_delta" field.
func PointsDeltaEQ(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldPointsDelta, v))
}

// PointsDeltaNEQ applies the NEQ predicate on the "points_delta" field.
func PointsDeltaNEQ(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldPointsDelta, v))
}

// PointsDeltaIn applies the In predicate on the "points_delta" field.
func PointsDeltaIn(vs ...int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldPointsDelta, vs...))
}

// PointsDeltaNotIn applies the NotIn predicate on the "points_delta" field.
func PointsDeltaNotIn(vs ...int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldPointsDelta, vs...))
}

// PointsDeltaGT applies the GT predicate on the "points_delta" field.
func PointsDeltaGT(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldPointsDelta, v))
}

// PointsDeltaGTE applies the GTE predicate on the "points_delta" field.
func PointsDeltaGTE(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldPointsDelta, v))
}

// PointsDeltaLT applies the LT predicate on the "points_delta" field.
func PointsDeltaLT(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldPointsDelta, v))
}

// PointsDeltaLTE applies the LTE predicate on the "points_delta" field.
func PointsDeltaLTE(v int32) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldPointsDelta, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v int16) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldKind, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PointTransaction {
	return predicate.PointTransaction(sql.FieldContainsFold(FieldReason, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShopMember applies the HasEdge predicate on the "shop_member" edge.
func HasShopMember() predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ShopMemberTable, ShopMemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopMemberWith applies the HasEdge predicate on the "shop_member" edge with a given conditions (other predicates).
func HasShopMemberWith(preds ...predicate.ShopMember) predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := newShopMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.Order) predicate.PointTransaction {
	return predicate.PointTransaction(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PointTransaction) predicate.PointTransaction {
	return predicate.PointTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PointTransaction) predicate.PointTransaction {
	return predicate.PointTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PointTransaction) predicate.PointTransaction {
	return predicate.PointTransaction(sql.NotPredicates(p))
}
