// Package schema — payment entities (change payment-integration, design
// D1–D10). payments is shop-owned tenant data and is registered in
// api/internal/tenant.tenantOwned; it carries a direct shop_id column so
// the interceptor/hook can scope it (same convention as order/cart/catalog).
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Payment is one payment attempt against an Order (design D3). Unlike
// OrderItem's product_id/sku_id (deliberately edge-less/FK-less
// informational snapshots — order-management design D4), Payment's order_id
// is a real, required FK: a payment record's entire reason to exist is "this
// money belongs to that order", not a point-in-time display snapshot, and
// there is no order-deletion endpoint today. No OnDelete annotation is set,
// so Postgres's default NO ACTION applies — deleting an order with existing
// payment rows is blocked rather than cascading them away, protecting the
// financial audit trail (more conservative than OrderItem's Cascade, and
// deliberately so).
//
// An order MAY have many payments (first attempt fails, retry succeeds) —
// order_id carries no uniqueness constraint. The (provider, provider_reference)
// pair MUST be globally unique: it is the only lookup key the webhook route
// has available, since that route runs without tenant context (design D7).
type Payment struct {
	ent.Schema
}

func (Payment) Mixin() []ent.Mixin {
	return []ent.Mixin{TimeMixin{}}
}

func (Payment) Fields() []ent.Field {
	return []ent.Field{
		field.Int("shop_id"),
		field.Int("order_id"),
		// provider (design D1/D2): the Provider.Name() that created this
		// attempt, e.g. "mock". Also the {provider} webhook path segment.
		field.String("provider").MaxLen(32).SchemaType(map[string]string{dialect.Postgres: "varchar(32)"}).NotEmpty(),
		// provider_reference (design D3/D6/D7): the provider-side
		// transaction identifier, generated at InitiatePayment time and
		// echoed back by the webhook. The sole idempotent webhook lookup
		// key (with provider) — see the unique index below.
		field.String("provider_reference").MaxLen(191).SchemaType(map[string]string{dialect.Postgres: "varchar(191)"}).NotEmpty(),
		// Money: integer minor units, BIGINT/int64 (product-catalog design
		// D1 convention). Always equals the order's total_amount at the time
		// this attempt was created — this change supports full-amount
		// payment only (design Non-Goals); the invariant amount <=
		// order.total_amount is enforced by payment.Service, not a DB CHECK
		// (Postgres CHECK cannot reference another table).
		field.Int64("amount"),
		field.String("currency").MaxLen(3).SchemaType(map[string]string{dialect.Postgres: "varchar(3)"}).NotEmpty(),
		// status (design D5): 0 pending / 1 succeeded / 2 failed / 3
		// refunded. This change's only program-driven transitions are
		// pending->succeeded and pending->failed (via
		// payment.Service.HandleWebhook); refunded is reserved for a future
		// refunds change, same reasoning as orders.payment_status below.
		field.Int16("status").Default(0),
	}
}

func (Payment) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("shop", Shop.Type).Unique().Required().Field("shop_id"),
		// One-directional real FK to Order (see type doc comment for why
		// this deliberately differs from OrderItem's edge-less product_id/
		// sku_id). No Ref/inverse edge on Order — declared entirely here,
		// so order.go does not need to change.
		edge.To("order", Order.Type).Unique().Required().Field("order_id"),
	}
}

func (Payment) Indexes() []ent.Index {
	return []ent.Index{
		// Idempotent webhook lookup key (design D6/D7) — MUST be unique:
		// provider_reference is generated by us (or the real provider) to be
		// unique per attempt, and this is the only way the tenant-context-
		// free webhook route can locate the right row.
		index.Fields("provider", "provider_reference").Unique(),
		index.Fields("shop_id", "order_id"),
	}
}

func (Payment) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{
			Checks: map[string]string{
				"payments_amount_check": "amount > 0",
				"payments_status_check": "status IN (0, 1, 2, 3)",
			},
		},
	}
}
